import type { DesignSystemEntry } from '../types';

/**
 * Atom Registry
 *
 * Atoms are the smallest, indivisible UI elements. They are rarely displayed
 * independently on a page — they exist to be composed into molecules and organisms.
 */
export const atoms: DesignSystemEntry[] = [
  {
    name: 'Button',
    description: 'Interactive button with primary, secondary, ghost, and danger variants in sm/md/lg sizes.',
    tier: 'atom',
    filePath: 'src/components/Button.tsx',
    usedIn: [
      'StatsOverview', 'Dashboard', 'Modal', 'RangeSelector',
      'EmployeeEditorModal', 'UserEditorModal', 'HolidayEditorModal',
      'CompanyEditorModal', 'ProjectEditorModal', 'ProfileEditorModal',
      'RateEditModal', 'LegalModal', 'HolidaysPage', 'UsersPage',
    ],
    introducedIn: 'Task 014',
  },
  {
    name: 'Input',
    description: 'Form input with label, error, helperText, startAddon/endAddon, and sm/md/lg sizes.',
    tier: 'atom',
    filePath: 'src/components/Input.tsx',
    usedIn: [
      'EmployeeEditorModal', 'UserEditorModal', 'HolidayEditorModal',
      'CompanyEditorModal', 'ProjectEditorModal', 'RateEditModal',
    ],
    introducedIn: 'Task 015',
  },
  {
    name: 'Select',
    description: 'Dropdown select with search, custom rendering, and keyboard navigation.',
    tier: 'atom',
    filePath: 'src/components/Select.tsx',
    usedIn: [
      'EmployeeEditorModal', 'HolidaysPage', 'RangeSelector',
      'BillingRatesTable', 'BillingsPage',
    ],
  },
  {
    name: 'MultiSelect',
    description: 'Multi-selection dropdown with checkboxes and badge count.',
    tier: 'atom',
    filePath: 'src/components/MultiSelect.tsx',
    usedIn: ['BillingsPage'],
  },
  {
    name: 'Checkbox',
    description: 'Checkbox input with label, indeterminate state, and size variants.',
    tier: 'atom',
    filePath: 'src/components/Checkbox.tsx',
    usedIn: ['BillingRatesTable'],
    introducedIn: 'Task 041',
  },
  {
    name: 'Toggle',
    description: 'Boolean switch with label and optional description text.',
    tier: 'atom',
    filePath: 'src/components/Toggle.tsx',
    usedIn: ['UserEditorModal'],
    introducedIn: 'Task 019',
  },
  {
    name: 'Card',
    description: 'Container with default, elevated, bordered, and subtle variants; none/sm/md/lg padding.',
    tier: 'atom',
    filePath: 'src/components/Card.tsx',
    usedIn: [
      'Dashboard', 'DashboardChartsRow', 'UnderHoursModal',
      'InvestorDashboardPage', 'FormulasPage',
    ],
    introducedIn: 'Task 015',
  },
  {
    name: 'Badge',
    description: 'Status label with default, success, warning, error, and info variants in sm/md sizes.',
    tier: 'atom',
    filePath: 'src/components/Badge.tsx',
    usedIn: [
      'BillingRatesTable', 'ResourceTable', 'EmployeePerformance',
      'HolidayCalendar',
    ],
    introducedIn: 'Task 015',
  },
  {
    name: 'Spinner',
    description: 'Animated loading indicator in sm/md/lg sizes with default and white color options.',
    tier: 'atom',
    filePath: 'src/components/Spinner.tsx',
    usedIn: [
      'Dashboard', 'EmployeesPage', 'RatesPage', 'InvestorDashboardPage',
      'HolidaysPage', 'BillingsPage', 'RevenuePage', 'EOMReportsPage',
    ],
    introducedIn: 'Task 014',
  },
  {
    name: 'Modal',
    description: 'Dialog overlay with header, scrollable body, optional sticky header, and footer actions.',
    tier: 'atom',
    filePath: 'src/components/Modal.tsx',
    usedIn: [
      'EmployeeEditorModal', 'UserEditorModal', 'HolidayEditorModal',
      'CompanyEditorModal', 'ProjectEditorModal', 'RateEditModal',
      'ProfileEditorModal', 'LegalModal', 'UnderHoursModal',
    ],
  },
  {
    name: 'Alert',
    description: 'Subtle message box with error or info icon variants.',
    tier: 'atom',
    filePath: 'src/components/Alert.tsx',
    usedIn: ['RatesPage', 'LoginPage'],
    introducedIn: 'Task 019',
  },
  {
    name: 'Avatar',
    description: 'Circular user avatar with image, initials fallback, and size variants.',
    tier: 'atom',
    filePath: 'src/components/Avatar.tsx',
    usedIn: ['MainHeader', 'ProfileEditorModal'],
  },
  {
    name: 'AvatarUpload',
    description: 'Avatar with hover overlay for uploading and cropping a new image.',
    tier: 'atom',
    filePath: 'src/components/AvatarUpload.tsx',
    usedIn: ['ProfileEditorModal'],
  },
  {
    name: 'ChevronIcon',
    description: 'Directional chevron SVG with left/right/up/down rotation and animated transitions.',
    tier: 'atom',
    filePath: 'src/components/ChevronIcon.tsx',
    usedIn: [
      'DateCycle', 'Accordion', 'AccordionNested', 'AccordionFlat',
      'AccordionListTable',
    ],
  },
  {
    name: 'Icon',
    description: 'Generic SVG icon wrapper for inline icons.',
    tier: 'atom',
    filePath: 'src/components/Icon.tsx',
    usedIn: ['Alert'],
  },
  {
    name: 'NavItem',
    description: 'Navigation link with active indicator bar and hover transition.',
    tier: 'atom',
    filePath: 'src/components/NavItem.tsx',
    usedIn: ['MainHeader'],
  },
  {
    name: 'MetricCard',
    description: 'Stat display card with title, value, optional status dot, loading state, and action button.',
    tier: 'atom',
    filePath: 'src/components/MetricCard.tsx',
    usedIn: [
      'StatsOverview', 'EmployeesPage', 'EmployeeManagementPage',
      'RatesPage', 'HolidaysPage', 'UsersPage', 'InvestorDashboardPage',
      'UnderHoursModal',
    ],
  },
  {
    name: 'DatePicker',
    description: 'Date input with inline calendar dropdown, month/year navigation, and keyboard support.',
    tier: 'atom',
    filePath: 'src/components/DatePicker.tsx',
    usedIn: ['HolidayEditorModal', 'BillingsPage'],
    introducedIn: 'Task 018',
  },
  {
    name: 'MonthPicker',
    description: 'Month-level date picker for selecting year/month combinations.',
    tier: 'atom',
    filePath: 'src/components/MonthPicker.tsx',
    usedIn: ['BillingsPage'],
  },
  {
    name: 'DropdownMenu',
    description: 'Context menu with icon-button or text trigger, positioned dynamically.',
    tier: 'atom',
    filePath: 'src/components/DropdownMenu.tsx',
    usedIn: ['RangeSelector', 'BillingRatesTable'],
  },
  {
    name: 'Accordion',
    description: 'Expandable section with chevron toggle and header/content areas.',
    tier: 'atom',
    filePath: 'src/components/Accordion.tsx',
    usedIn: ['DiagnosticsPage'],
    introducedIn: 'Task 018',
  },
  {
    name: 'AccordionNested',
    description: 'Three-level accordion hierarchy (project > resource > task) with left border lines.',
    tier: 'atom',
    filePath: 'src/components/AccordionNested.tsx',
    usedIn: ['EmployeePerformance', 'RevenuePage'],
    introducedIn: 'Task 018',
  },
  {
    name: 'AccordionFlat',
    description: 'Two-level accordion with tabular content, column headers, groupable rows, and footer.',
    tier: 'atom',
    filePath: 'src/components/AccordionFlat.tsx',
    usedIn: ['BillingRatesTable'],
    introducedIn: 'Task 018',
  },
  {
    name: 'AccordionListTable',
    description: 'Accordion with list-table hybrid content for expandable rows with columns.',
    tier: 'atom',
    filePath: 'src/components/AccordionListTable.tsx',
    usedIn: ['UnderHoursModal'],
  },
  {
    name: 'Markdown',
    description: 'Renders Markdown-formatted text as styled HTML.',
    tier: 'atom',
    filePath: 'src/components/Markdown.tsx',
    usedIn: ['ChatMessage', 'LegalPage'],
  },
  {
    name: 'TypingIndicator',
    description: 'Animated bouncing dots indicating that AI is typing a response.',
    tier: 'atom',
    filePath: 'src/components/TypingIndicator.tsx',
    usedIn: ['AIChatWindow'],
  },
  // Chart atoms
  {
    name: 'BarChartAtom',
    description: 'Horizontal bar chart for resource hours distribution using Recharts.',
    tier: 'atom',
    filePath: 'src/components/atoms/charts/BarChartAtom.tsx',
    usedIn: ['DashboardChartsRow'],
  },
  {
    name: 'PieChartAtom',
    description: 'Donut/pie chart for data distribution using Recharts.',
    tier: 'atom',
    filePath: 'src/components/atoms/charts/PieChartAtom.tsx',
    usedIn: ['DashboardChartsRow'],
  },
  {
    name: 'LineGraphAtom',
    description: 'Line chart for cumulative Target/Budget/Revenue trends using Recharts.',
    tier: 'atom',
    filePath: 'src/components/atoms/charts/LineGraphAtom.tsx',
    usedIn: ['DashboardChartsRow', 'InvestorDashboardPage'],
  },
  {
    name: 'CAGRChartAtom',
    description: 'Compound Annual Growth Rate bar chart visualization.',
    tier: 'atom',
    filePath: 'src/components/atoms/charts/CAGRChartAtom.tsx',
    usedIn: ['DashboardChartsRow'],
  },
  {
    name: 'DailyHoursChart',
    description: 'Stacked bar chart showing daily hours by employee across a month.',
    tier: 'atom',
    filePath: 'src/components/atoms/charts/DailyHoursChart.tsx',
    usedIn: ['Dashboard'],
  },
  // Table atoms
  {
    name: 'BurnGrid',
    description: 'Daily hours grid showing employee hours per day with under-hours highlighting.',
    tier: 'atom',
    filePath: 'src/components/atoms/BurnGrid.tsx',
    usedIn: ['BurnPage'],
  },
  {
    name: 'ProjectHierarchyTable',
    description: 'Expandable table showing company > project > resource > task hierarchy.',
    tier: 'atom',
    filePath: 'src/components/atoms/ProjectHierarchyTable.tsx',
    usedIn: ['ProjectsPage'],
  },
  {
    name: 'RevenueTable',
    description: 'Expandable revenue table with company > project > resource > task breakdown.',
    tier: 'atom',
    filePath: 'src/components/atoms/RevenueTable.tsx',
    usedIn: ['RevenuePage'],
  },
];
