-- ============================================================================
-- Re-categorization of existing Miscellaneous rows (GENERATED — review then apply)
-- ============================================================================
-- Generated by scripts/expenses/recategorize.mjs at 2026-07-02T08:20:14.078Z
-- Rule set: live prod rules + pending migration 128 delta.
-- 80 row(s) would move out of Miscellaneous. category_source is set
-- to the matched rule type. The WHERE guard keeps this idempotent and never
-- overwrites a manual assignment.
-- ============================================================================

BEGIN;

UPDATE public.expenses SET category_id = 11, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '12305e95-6ce5-4e4d-ba4f-0b41629e076f' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '347134b3-5bb8-4117-89ae-640951c2176d' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '58f228c9-afdd-410a-b9b7-e7e061391a73' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '7703dc81-0af7-4afb-95d1-72675f576bc6' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '17fdd1b0-3e95-41cc-b469-f59439d438b3' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'ff9edc74-76b5-4de6-adba-a2868a1acbe6' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '77c18e53-9969-45b4-8e53-01c3291a93a1' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '211543a0-eb38-4a8d-bef4-36dbc02142cd' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '6c297c49-41bf-499e-b5b7-bc5dc926399d' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '74e78f0f-f474-46d5-afaa-ee7a2930a1c8' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'cd05c2c6-9e30-4ca4-b1fe-2de0633e09ee' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '54b984ed-d157-4efc-866c-67d8e29e5d49' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'f2feaece-2cbb-4a06-a4b5-6477d48c95f3' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '31d0bd1b-41de-4752-8d66-6bcecb467e2f' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'a7234653-376d-4f41-bba9-c68d0470cb4e' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '8b746810-57a1-417c-a2b4-d4fb453783bc' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '67fc24d0-142c-4e58-9087-e04a4eb4cdb3' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '24a55e7d-da03-4b80-a89e-e99758b5f84d' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 6, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '8a0b5bd1-4c08-4d17-9179-e65ac5c60b3a' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '9dd8fe85-c1e5-4e3c-a789-83acb1a11678' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '700b2a9d-edf7-4dce-bfa0-4857a6b60365' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'a098051d-769e-45f7-bca6-342638908653' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'd351290f-e0f1-4a33-ad06-d40bc15f9bc5' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 9, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '607af6c5-4833-4cf5-9c76-677c84106a79' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 11, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '1eb8e1d2-eb79-4cc1-be4a-09fb634b3aa0' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '6e1b9b8c-f60d-4def-8c63-5c133fdd8919' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '353c4cf6-dc31-4141-bba1-ea93fe5fa630' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '80058a2a-9c8b-4a06-86b8-13a1ae7e0aec' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'bc89f8da-a116-4a9a-995e-0c1486efcc05' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'ad8497c3-efc8-4fec-8a12-3de3ce69eb6e' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'a40c8a4b-0d74-4710-b899-75191a67be65' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 3, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'f27666eb-b9b0-420d-940b-edf7d1df49ed' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '153bd559-b884-4f3c-a3b9-e61687ae3fd0' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '978d9798-334e-49e7-92fa-74f9e25756e8' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '861c94c8-1c99-4135-90ca-e78bdf5a74ce' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '36a9fa01-94ba-46cd-92be-6babb7e9ccb6' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '9d56fe6c-e851-4e09-ab11-c24fc4fe24fc' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '90d7bccc-a4bb-4a5b-9423-68accaee7879' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'f7b51cad-162b-4eb2-9335-c6aef4016fa8' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '00bf577c-b27c-4b4e-8a86-fcf38f0a6844' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'f70be308-0399-418b-9341-897cecc808d0' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 6, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '23e85f8c-9b5f-4c33-a2f8-ed25bf812f28' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 11, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '106ff118-f41f-4284-b04a-cc2532857266' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'c3500727-5f78-46b7-9394-af677efc398f' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '76a160c4-4371-4eca-a5f0-a041444d15e7' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '93af37f9-8242-48e9-9c65-f900bbb7918c' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'ac68e9dd-7383-4cba-8524-87397a821157' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '7ca2d028-f859-439a-8677-ae6f32ca921c' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'b554924f-9102-48ee-9eef-0e620f121394' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 3, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '90c93ad3-d196-4a1f-acf3-fb8d44b90834' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'cf520814-64b6-4dc1-91ca-cb1389fc877a' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'df28ab9c-15ee-40e9-8b2d-173263310c93' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'd5498285-d603-4758-a102-b8eb9e9e9764' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'a613921a-99d8-43d6-8eff-9e36f1707f4e' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'f7e342d7-d9b7-4be2-ab61-9d869b405a8b' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 3, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'c310297c-4119-4683-9492-999b2533b2db' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'dd0a35f7-eba5-48b1-bf90-3c154f0c6d56' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'c504fd0b-f57e-4a8b-82ad-10a3ee32da30' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'a34390eb-6203-41a9-a1a2-155896a06d3b' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '9e625f9c-ed01-45ab-9f74-d89bc5b854ac' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '4d9e91ad-1736-4d1f-9443-5dcd3b100ed0' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '631c3173-e377-45bd-9325-1f73b9838fe0' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'f31a5665-0f36-486a-9a3a-d37623e11008' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '43928f32-d712-4669-bf78-08130e79dbf8' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '0590aef0-2269-4a33-ba6f-71262a6441e2' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '30e290b6-3838-4c86-a6ef-9affb4aba661' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '7aad2a09-4c1f-4a6b-8748-6bbda59474e3' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'e1bf7f58-4a62-4a84-a33e-07d38e60b627' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '4f1dc74c-b0c4-420c-a240-56a915f03a13' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '1c542279-20d4-4248-a797-ab841655fd42' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'ca3d06e7-175a-40eb-a3cb-59ef77587f61' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'be472480-f4f3-48f0-a0f9-443691fbf5c8' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'ac43da94-fb3b-4bdc-be74-30cd28d7f36a' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '83b2f6b7-744e-49a7-86f9-d85036a5c8d5' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = 'a3ba6fe7-e038-42dc-aced-2ae0c2ca753e' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 4, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '05333a1d-ccfd-4dd8-b04c-51f36a416645' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 6, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '39a623a9-575c-432e-9f09-c0b4343ad4c0' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 6, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '14a63f5e-cb4e-4b06-8e9d-3e0dd43f456c' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 9, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '6cd7f304-5d75-447c-a6e8-942447ea3320' AND category_id = 15 AND category_source <> 'manual';
UPDATE public.expenses SET category_id = 11, category_source = 'keyword_rule', needs_review = FALSE WHERE id = '615a6436-3c48-4ea1-bc9d-6ac4e199c514' AND category_id = 15 AND category_source <> 'manual';

COMMIT;
