-- ============================================================================
-- Migration 071: Weekly Reports — Table, Storage, RLS, Availability View
-- ============================================================================
-- Purpose: Create the infrastructure for weekly CSV revenue report storage
-- and tracking. Reports are generated by the send-weekly-revenue-report edge
-- function and stored in a private bucket for download/resend.
--
-- Changes:
--   1. weekly_reports table (metadata + storage path for each company-week CSV)
--   2. weekly-reports private storage bucket (CSV files)
--   3. RLS policies (authenticated SELECT, service_role write)
--   4. v_weekly_report_availability view (company-weeks with timesheet data)
--   5. Updated_at trigger (reuses existing update_updated_at_column)
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1: CREATE weekly_reports TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS weekly_reports (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id          UUID NOT NULL REFERENCES companies(id),
    company_name        TEXT NOT NULL,                          -- snapshot at generation time
    week_start          DATE NOT NULL,
    week_end            DATE NOT NULL,
    report_year         INTEGER NOT NULL,
    report_month        INTEGER NOT NULL,
    total_hours         NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_revenue_cents BIGINT NOT NULL DEFAULT 0,
    project_count       INTEGER NOT NULL DEFAULT 0,
    task_count          INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_weekly_month_range CHECK (report_month BETWEEN 1 AND 12),
    storage_path        TEXT,
    file_size_bytes     BIGINT,
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at             TIMESTAMPTZ,
    sent_to             TEXT[],
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT uq_weekly_company_week UNIQUE (company_id, week_start),
    CONSTRAINT chk_weekly_date_range CHECK (week_end = week_start + INTERVAL '6 days')
);

COMMENT ON TABLE weekly_reports IS
    'Weekly revenue report metadata. Each row corresponds to one CSV file '
    'stored in the weekly-reports bucket. Reports are generated weekly by '
    'the send-weekly-revenue-report edge function.';

-- ============================================================================
-- STEP 2: INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_weekly_reports_year_month ON weekly_reports (report_year, report_month);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_company ON weekly_reports (company_id);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_generated_at ON weekly_reports (generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_week_start ON weekly_reports (week_start DESC);

-- ============================================================================
-- STEP 3: UPDATED_AT TRIGGER
-- ============================================================================

DROP TRIGGER IF EXISTS set_weekly_reports_updated_at ON weekly_reports;
CREATE TRIGGER set_weekly_reports_updated_at
    BEFORE UPDATE ON weekly_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- STEP 4: RLS POLICIES
-- ============================================================================

ALTER TABLE weekly_reports ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read weekly reports
DROP POLICY IF EXISTS "Authenticated users can read weekly reports" ON weekly_reports;
CREATE POLICY "Authenticated users can read weekly reports"
    ON weekly_reports FOR SELECT
    TO authenticated
    USING (true);

-- Service role can manage weekly reports (generation, re-generation)
DROP POLICY IF EXISTS "Service role can manage weekly reports" ON weekly_reports;
CREATE POLICY "Service role can manage weekly reports"
    ON weekly_reports FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- ============================================================================
-- STEP 5: GRANTS
-- ============================================================================

GRANT SELECT ON weekly_reports TO authenticated;
GRANT ALL ON weekly_reports TO service_role;

-- ============================================================================
-- STEP 6: CREATE weekly-reports STORAGE BUCKET (private)
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'weekly-reports',
    'weekly-reports',
    false,                  -- private bucket
    52428800,               -- 50MB limit
    ARRAY['text/csv', 'application/csv']
)
ON CONFLICT (id) DO UPDATE SET
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Authenticated users can download (SELECT) weekly report files
DROP POLICY IF EXISTS "Authenticated users can read weekly report files" ON storage.objects;
CREATE POLICY "Authenticated users can read weekly report files"
    ON storage.objects
    FOR SELECT
    TO authenticated
    USING (bucket_id = 'weekly-reports');

-- Service role can upload/update/delete CSV files
DROP POLICY IF EXISTS "Service role can insert weekly report files" ON storage.objects;
CREATE POLICY "Service role can insert weekly report files"
    ON storage.objects
    FOR INSERT
    TO service_role
    WITH CHECK (bucket_id = 'weekly-reports');

DROP POLICY IF EXISTS "Service role can update weekly report files" ON storage.objects;
CREATE POLICY "Service role can update weekly report files"
    ON storage.objects
    FOR UPDATE
    TO service_role
    USING (bucket_id = 'weekly-reports');

DROP POLICY IF EXISTS "Service role can delete weekly report files" ON storage.objects;
CREATE POLICY "Service role can delete weekly report files"
    ON storage.objects
    FOR DELETE
    TO service_role
    USING (bucket_id = 'weekly-reports');

-- ============================================================================
-- STEP 7: CREATE v_weekly_report_availability VIEW
-- ============================================================================
-- Enumerates all company-weeks from 2026 onward that have timesheet entries,
-- left-joined with any existing weekly_reports records.
--
-- Week computation uses ISO weeks starting on Monday.
-- date_trunc('week', ...) in PostgreSQL truncates to Monday by default (ISO 8601).

CREATE OR REPLACE VIEW v_weekly_report_availability AS
WITH company_weeks AS (
    SELECT DISTINCT
        p.company_id,
        date_trunc('week', te.work_date)::DATE AS week_start,
        (date_trunc('week', te.work_date) + INTERVAL '6 days')::DATE AS week_end
    FROM v_timesheet_entries te
    JOIN projects p ON p.project_id = te.project_id
    WHERE p.company_id IS NOT NULL
      AND te.work_date >= '2026-01-01'::date
)
SELECT
    cw.company_id,
    c.client_id,
    COALESCE(c.display_name, c.client_name) AS company_name,
    EXTRACT(YEAR FROM cw.week_start)::INTEGER AS report_year,
    EXTRACT(MONTH FROM cw.week_start)::INTEGER AS report_month,
    cw.week_start,
    cw.week_end,
    wr.id AS report_id,
    wr.generated_at,
    wr.storage_path,
    wr.file_size_bytes,
    wr.total_hours,
    wr.total_revenue_cents,
    wr.project_count,
    wr.task_count,
    wr.sent_at,
    wr.sent_to,
    CASE WHEN wr.id IS NOT NULL THEN true ELSE false END AS has_report
FROM company_weeks cw
JOIN companies c ON c.id = cw.company_id
LEFT JOIN weekly_reports wr ON wr.company_id = cw.company_id AND wr.week_start = cw.week_start
ORDER BY cw.week_start DESC, company_name;

COMMENT ON VIEW v_weekly_report_availability IS
    'Shows all company-weeks from 2026 onward that have timesheet entries. '
    'Includes generation/send status from weekly_reports. '
    'Uses ISO weeks (Monday start) via date_trunc.';

GRANT SELECT ON v_weekly_report_availability TO authenticated;
GRANT SELECT ON v_weekly_report_availability TO service_role;

-- ============================================================================
-- STEP 8: VERIFICATION
-- ============================================================================

DO $$
DECLARE
    v_table_exists BOOLEAN;
    v_bucket_exists BOOLEAN;
    v_view_exists BOOLEAN;
    v_policy_count INTEGER;
BEGIN
    -- Verify table
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'weekly_reports'
    ) INTO v_table_exists;

    -- Verify bucket
    SELECT EXISTS (
        SELECT 1 FROM storage.buckets WHERE id = 'weekly-reports'
    ) INTO v_bucket_exists;

    -- Verify view
    SELECT EXISTS (
        SELECT 1 FROM information_schema.views
        WHERE table_schema = 'public' AND table_name = 'v_weekly_report_availability'
    ) INTO v_view_exists;

    -- Count policies
    SELECT COUNT(*) INTO v_policy_count
    FROM pg_policies
    WHERE tablename = 'weekly_reports';

    RAISE NOTICE 'Migration 071 Complete:';
    RAISE NOTICE '  - weekly_reports table: %', CASE WHEN v_table_exists THEN 'CREATED' ELSE 'MISSING' END;
    RAISE NOTICE '  - weekly-reports storage bucket: %', CASE WHEN v_bucket_exists THEN 'CREATED' ELSE 'MISSING' END;
    RAISE NOTICE '  - v_weekly_report_availability view: %', CASE WHEN v_view_exists THEN 'CREATED' ELSE 'MISSING' END;
    RAISE NOTICE '  - RLS policies on weekly_reports: %', v_policy_count;
    RAISE NOTICE '  - updated_at trigger attached';

    IF NOT v_table_exists THEN
        RAISE WARNING 'weekly_reports table was not created!';
    END IF;
    IF NOT v_bucket_exists THEN
        RAISE WARNING 'weekly-reports storage bucket was not created!';
    END IF;
END $$;

COMMIT;
