-- =============================================================================
-- Migration 078: Create sync_alerts table for BambooHR reconciliation alerts
-- =============================================================================
-- Stores discrepancy alerts generated by the sync-bamboohr-timeoff Edge Function:
--
--   1. timeoff_days_mismatch — BambooHR total days != Manifest employee_time_off totals
--   2. unmatched_resource    — A Manifest resource has no linked BambooHR employee
--
-- Alerts are auto-resolved when the underlying data is fixed on next sync.
-- Users can dismiss alerts from the dashboard; dismissed alerts reappear if
-- the underlying data changes.
-- =============================================================================

CREATE TABLE sync_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_type TEXT NOT NULL,              -- 'timeoff_days_mismatch' | 'unmatched_resource'
  severity TEXT NOT NULL DEFAULT 'warning',  -- 'warning' | 'error'
  title TEXT NOT NULL,
  detail TEXT,
  entity_type TEXT,                      -- 'employee' | 'resource'
  entity_id TEXT,                        -- bamboo_employee_id or resource UUID
  entity_name TEXT,
  metadata JSONB DEFAULT '{}',           -- { bamboo_days, manifest_days, etc. }
  dismissed_at TIMESTAMPTZ,              -- NULL = not dismissed
  dismissed_by UUID,                     -- auth.uid() of user who dismissed
  resolved_at TIMESTAMPTZ,              -- NULL = active, set when auto-resolved
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fetching active (unresolved) alerts efficiently
CREATE INDEX idx_sync_alerts_active
  ON sync_alerts (alert_type)
  WHERE resolved_at IS NULL;

-- Prevent duplicate active alerts for the same entity
CREATE UNIQUE INDEX idx_sync_alerts_unique_active
  ON sync_alerts (alert_type, entity_id)
  WHERE resolved_at IS NULL;

-- =============================================================================
-- Row Level Security
-- =============================================================================
ALTER TABLE sync_alerts ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read all alerts (for dashboard display)
CREATE POLICY "Allow authenticated read access to sync_alerts"
  ON sync_alerts
  FOR SELECT
  TO authenticated
  USING (true);

-- Authenticated users can update alerts (for dismiss functionality)
CREATE POLICY "Allow authenticated update access to sync_alerts"
  ON sync_alerts
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Service role has full access (for Edge Function insert/delete/update)
CREATE POLICY "Allow service role full access to sync_alerts"
  ON sync_alerts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
