-- ============================================================================
-- Migration 127: Expense Mapping Seed (GENERATED — do not hand-edit)
-- ============================================================================
-- Generated by scripts/expenses/mine_expenses.py from the B Team 2025-AP RAW
-- bank exports (read-only), per CANONICAL CONTRACT v2. Ingest matches raw
-- Cyrillic rows, so all keys/patterns are the RAW Cyrillic fields.
--   - expense_translation_dict  key = normalize(Основание за плащане + ' ' +
--                               Описание на операцията); en = romanized form
--   - expense_vendor_rules       pattern = RAW Cyrillic Бенефициент (priority
--                               100); romanized english Vendor kept as
--                               secondary (priority 200). No category-15 rules.
--   - expense_keyword_rules      re-validated on RAW description text
--
-- Self-validation on the reference corpus:
--   dictionary hit rate (Cyrillic rows) = 1.0
--   vendor+keyword category agreement    = 0.9145
--   predicted Miscellaneous share        = 0.3176
-- Counts: 267 translation entries, 174 vendor rules (50 raw-cyr + 124 romanized), 39 keyword rules.
-- Idempotent (ON CONFLICT DO NOTHING); Cyrillic/apostrophes escaped via doubled quotes.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- expense_translation_dict
-- ----------------------------------------------------------------------------
INSERT INTO public.expense_translation_dict
    (normalized_key, bg_sample, en_translation, occurrences, source)
VALUES
    ('SALARY # # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Salary 11 2025 Платежно нареждане извън банката', 'SALARY # # PLATEZHNO NAREZHDANE IZVAN BANKATA', 238, 'mined'),
    ('SALARY # # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Salary 11 2025 BLINK Платежно нареждане извън банката', 'SALARY # # BLINK PAYMENT ORDER OUTSIDE THE BANK', 232, 'mined'),
    ('BLINK ТАКСА ЗА МЕЖДУБАНКОВ ПРЕВОД', 'BLINK Такса за междубанков превод', 'BLINK TAKSA ZA MEZHDUBANKOV PREVOD', 190, 'mined'),
    ('ТАКСА ЗА МЕЖДУБАНКОВ ПРЕВОД', 'Такса за междубанков превод', 'TAKSA ZA MEZHDUBANKOV PREVOD', 159, 'mined'),
    ('ЗАПЛАТА # # SALARY # # ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'заплата 02 2026 salary 02 2026 Издаден вътр.банков превод', 'SALARY # # SALARY # # INTERNAL BANK TRANSFER ISSUED', 101, 'mined'),
    ('SALARY # # ЗАПЛАТА # # ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Salary 02 2026 Заплата 02 2026 Издаден вътр.банков превод', 'SALARY # # ZAPLATA # # INTERNAL BANK TRANSFER ISSUED', 81, 'mined'),
    ('AZV-COMMISSION # USD FOR GPP TRANSACTION REF.: #/ТАКСИ ПОЛУЧЕНИ ВАЛУТНИ ПРЕВОДИ', 'AZV-Commission 4162.50 USD for GPP transaction Ref.: 6064200025/Такси получени валутни преводи', 'AZV-COMMISSION # USD FOR GPP TRANSACTION REF.: #/FEES FOR RECEIVED FOREIGN CURRENCY TRANSFERS', 61, 'mined'),
    ('ЗАПЛАТА # # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Заплата 12 2025 BLINK Платежно нареждане извън банката', 'ZAPLATA # # BLINK PAYMENT ORDER OUTSIDE THE BANK', 58, 'mined'),
    ('SALARY ASPAROUH # # ЗАПЛАТА ЗА М. # # ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'salary Asparouh 02 2026 заплата за м. 02 2026 Издаден вътр.банков превод', 'SALARY ASPAROUH # # SALARY ZA M. # # INTERNAL BANK TRANSFER ISSUED', 53, 'mined'),
    ('ЗАПЛАТА # # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Заплата 12 2025 Платежно нареждане извън банката', 'ZAPLATA # # PLATEZHNO NAREZHDANE IZVAN BANKATA', 50, 'mined'),
    ('ПОС # USD АВТ.КОД:#-TAGGABLE PHOTOS/CHICAGO /USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 0.40 USD авт.код:320684-TAGGABLE PHOTOS/CHICAGO /USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-TAGGABLE PHOTOS/CHICAGO /USA/PAN:#****#/CT:# CARD TRANSACTION', 46, 'mined'),
    ('ПРОФ Ф-РА # WATER, OFFICE ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'проф ф-ра 9000033449 Water, Office Издаден вътр.банков превод', 'PROFORMA INVOICE # WATER, OFFICE INTERNAL BANK TRANSFER ISSUED', 44, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-CLAUDE.AI SUBSCRIPTION/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 180.00 EUR авт.код:258618-CLAUDE.AI SUBSCRIPTION/SAN FRANCISCO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-CLAUDE.AI SUBSCRIPTION/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 41, 'mined'),
    ('Ф-РА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ф-ра 0000001037 Платежно нареждане извън банката', 'INVOICE # PLATEZHNO NAREZHDANE IZVAN BANKATA', 38, 'mined'),
    ('Ф-РА # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ф-ра 0000000526 BLINK Платежно нареждане извън банката', 'INVOICE # BLINK PAYMENT ORDER OUTSIDE THE BANK', 34, 'mined'),
    ('ПОС # USD АВТ.КОД:#-OPENAI *CHATGPT SUBSCR/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 200.00 USD авт.код:417190-OPENAI *CHATGPT SUBSCR/SAN FRANCISCO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-OPENAI *CHATGPT SUBSCR/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 32, 'mined'),
    ('SALARY # # ЗАПЛАТА # # ИЗХ.ПРЕВОД SEPA В ЕИП', 'Salary 02 2026 Заплата 02 2026 Изх.превод SEPA в ЕИП', 'SALARY # # ZAPLATA # # OUTGOING SEPA TRANSFER', 31, 'mined'),
    ('AZV-COMMISSION FOR GPP TRANSACTION REF.: #/ТАКСИ ИЗДАДЕНИ ВАЛУТНИ ПРЕВОДИ', 'AZV-Commission for GPP transaction Ref.: 6058100878/Такси издадени валутни преводи', 'AZV-COMMISSION FOR GPP TRANSACTION REF.: #/FEES FOR OUTGOING FOREIGN CURRENCY TRANSFERS', 28, 'mined'),
    ('ПОС # USD АВТ.КОД:#-CURSOR, AI POWERED IDE/NEW YORK/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 20.00 USD авт.код:700782-CURSOR, AI POWERED IDE/NEW YORK/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-CURSOR, AI POWERED IDE/NEW YORK/USA/PAN:#****#/CT:# CARD TRANSACTION', 28, 'mined'),
    ('ПОС # USD АВТ.КОД:#-WWW.TWILIO.COM/DUBLIN/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 23.94 USD авт.код:222558-WWW.TWILIO.COM/DUBLIN/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-WWW.TWILIO.COM/DUBLIN/IRL/PAN:#****#/CT:# CARD TRANSACTION', 27, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, EMAILOCTOPUS/LONDON/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 18.00 USD, авт.код:259444, EMAILOCTOPUS/LONDON/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, EMAILOCTOPUS/LONDON/PAN:#****#/CT:# CARD TRANSACTION', 27, 'mined'),
    ('CAR RENTAL ПРЕВОД ПО Ф-РА НАЕМ НА АВТОМОБИЛ ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Car rental превод по ф-ра наем на автомобил Издаден вътр.банков превод', 'CAR RENTAL INVOICE TRANSFER CAR RENTAL INTERNAL BANK TRANSFER ISSUED', 26, 'mined'),
    ('PAYMENT ON INVOICE ПЛАЩАНЕ ПО Ф-РА ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Payment on invoice плащане по ф-ра Издаден вътр.банков превод', 'PAYMENT ON INVOICE INVOICE PAYMENT INTERNAL BANK TRANSFER ISSUED', 26, 'mined'),
    ('ВНОСКИ ЗА ДЗПО ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Вноски за ДЗПО Платежно нареждане извън банката', 'SUPPLEMENTARY PENSION CONTRIBUTIONS PLATEZHNO NAREZHDANE IZVAN BANKATA', 26, 'mined'),
    ('ВНОСКИ ЗА ДОО ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Вноски за ДОО Платежно нареждане извън банката', 'SOCIAL SECURITY CONTRIBUTIONS PLATEZHNO NAREZHDANE IZVAN BANKATA', 26, 'mined'),
    ('ВНОСКИ ЗА ЗО ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Вноски за ЗО Платежно нареждане извън банката', 'HEALTH INSURANCE CONTRIBUTIONS PLATEZHNO NAREZHDANE IZVAN BANKATA', 26, 'mined'),
    ('ПОС # USD АВТ.КОД:#-BAMBOOHR HRIS/LINDON/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 250.00 USD авт.код:510726-BAMBOOHR HRIS/LINDON/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-BAMBOOHR HRIS/LINDON/USA/PAN:#****#/CT:# CARD TRANSACTION', 26, 'mined'),
    ('ПОС # USD АВТ.КОД:#-EMAILOCTOPUS/LONDON/GBR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 9.00 USD авт.код:497563-EMAILOCTOPUS/LONDON/GBR/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-EMAILOCTOPUS/LONDON/GBR/PAN:#****#/CT:# CARD TRANSACTION', 26, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, MIDJOURNEY INC./MIDJOURNEY.CO/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 30.00 USD, авт.код:474919, MIDJOURNEY INC./MIDJOURNEY.CO/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, MIDJOURNEY INC./MIDJOURNEY.CO/PAN:#****#/CT:# CARD TRANSACTION', 26, 'mined'),
    ('ДЪЛЖИМА ПЕРИОДИЧНА ТАКСА', 'Дължима периодична такса', 'RECURRING FEE DUE', 25, 'mined'),
    ('EHS # #/# #/# КОМУНАЛНО ПЛАЩАНЕ BBO', 'EHS 210044998247 473226785/10.02.20 26/10.02.2026 Комунално плащане BBO', 'EHS # #/# #/# UTILITY PAYMENT BBO', 24, 'mined'),
    ('ДОД ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ДОД Платежно нареждане извън банката', 'WITHHOLDING INCOME TAX PLATEZHNO NAREZHDANE IZVAN BANKATA', 24, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-A# BULGARIA LTD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 318.53 BGN авт.код:229591-A1 BULGARIA LTD/Sofia/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-A# BULGARIA LTD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 24, 'mined'),
    ('ПОГАСЯВ.НА Л-ВА ЗА РЕДОВНА ГЛАВНИЦА # BGN # ПОГАСЯВ.НА Л-ВА ЗА РЕДОВНА ГЛАВНИЦА', 'Погасяв.на л-ва за редовна главница 70001522532201 BGN 486.01 Погасяв.на л-ва за редовна главница', 'LOAN INTEREST REPAYMENT # BGN # LOAN INTEREST REPAYMENT', 24, 'mined'),
    ('ПОГАСЯВАНЕ НА ГЛАВНИЦА # BGN # ПОГАСЯВАНЕ НА ГЛАВНИЦА', 'Погасяване на главница 70001522532201 BGN 4144 Погасяване на главница', 'LOAN PRINCIPAL REPAYMENT # BGN # LOAN PRINCIPAL REPAYMENT', 24, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, OPENAI *CHATGPT SUBSCR/OPENAI.COM/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 200.00 USD, авт.код:469295, OPENAI *CHATGPT SUBSCR/OPENAI.COM/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, OPENAI *CHATGPT SUBSCR/OPENAI.COM/PAN:#****#/CT:# CARD TRANSACTION', 24, 'mined'),
    ('ДЕБИТ НОТА НОМЕР # HEALTH INSURANCE EMPLOYEES ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Дебит нота номер 290023790026 Health Insurance employees Издаден вътр.банков превод', 'DEBIT NOTE NUMBER # HEALTH INSURANCE EMPLOYEES INTERNAL BANK TRANSFER ISSUED', 23, 'mined'),
    ('ДЕБИТ НОТА НОМЕР # HEALTH INSURANCE SPOUSES ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Дебит нота номер 290024190026 Health Insurance spouses Издаден вътр.банков превод', 'DEBIT NOTE NUMBER # HEALTH INSURANCE SPOUSES INTERNAL BANK TRANSFER ISSUED', 23, 'mined'),
    ('ТАКСА ЗА ИЗХ.ПРЕВОД SEPA В ЕИП', 'Такса за изх.превод SEPA в ЕИП', 'TAKSA ZA OUTGOING SEPA TRANSFER', 23, 'mined'),
    ('BONUS ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Bonus Платежно нареждане извън банката', 'BONUS PLATEZHNO NAREZHDANE IZVAN BANKATA', 22, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-SUPERHOSTING.BG BGN/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 66.25 BGN авт.код:606806-SUPERHOSTING.BG BGN/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-SUPERHOSTING.BG BGN/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 22, 'mined'),
    ('ПОС # USD АВТ.КОД:#-GITHUB, INC./SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 0.79 USD авт.код:674854-GITHUB, INC./SAN FRANCISCO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-GITHUB, INC./SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 22, 'mined'),
    ('СОФИЙСКА ВОДА АД КЛ.НОМЕР # # ФАКТУРА # КОМУНАЛНО ПЛАЩАНЕ BBO', 'Софийска вода АД кл.номер 10055233 60 фактура 0000000147882296 Комунално плащане BBO', 'SOFIYSKA VODA AD KL.NOMER # # FAKTURA # UTILITY PAYMENT BBO', 22, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-FIGMA/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 60.00 EUR авт.код:797228-FIGMA/SAN FRANCISCO/USA/PAN:5408****6583/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-FIGMA/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 21, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-EPAY OFFICE#.BG/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 122.22 BGN авт.код:759246-ePay office1.bg/Sofia/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-EPAY OFFICE#.BG/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 20, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-INTUIT *QBOOKS ONLINE/#-#-#/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 27.00 EUR авт.код:430341-INTUIT *QBooks Online/800-446-8848/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-INTUIT *QBOOKS ONLINE/#-#-#/USA/PAN:#****#/CT:# CARD TRANSACTION', 20, 'mined'),
    ('Ф-РА # MULTISPORT ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 2000295985 Multisport Издаден вътр.банков превод', 'INVOICE # MULTISPORT INTERNAL BANK TRANSFER ISSUED', 20, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-INVEST - BG EOOD/HASKOVO/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 51.40 BGN авт.код:721890-INVEST - BG EOOD/HASKOVO/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-INVEST - BG EOOD/HASKOVO/PAN:#****#/CT:# CARD TRANSACTION', 18, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-KAFFEKAPSLEN/HASSELAGER/DNK/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 120.02 BGN авт.код:973519-KaffeKapslen/Hasselager/DNK/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-KAFFEKAPSLEN/HASSELAGER/DNK/PAN:#****#/CT:# CARD TRANSACTION', 18, 'mined'),
    ('ПОС # USD АВТ.КОД:#-APR*APPRIVER/#-#-#/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 411.40 USD авт.код:586362-APR*APPRIVER/850-932-5338/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-APR*APPRIVER/#-#-#/USA/PAN:#****#/CT:# CARD TRANSACTION', 18, 'mined'),
    ('ПОС # USD АВТ.КОД:#-FIGMA/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 24.00 USD авт.код:533596-FIGMA/SAN FRANCISCO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-FIGMA/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 18, 'mined'),
    ('AZV-MAIN ASSEMBLY CYPRUS LTD, PAYMENT ON INVOICE FOR AGENT SERVIC ES , GPP REF.: #, , #, REVOLT#XXX REVOLUT BANK UAB, LT #, THEMISTOKLI DERVI #, OFFICE # NICOSIA CYPRUS/ИЗДАВАНЕ НА ПРЕВОД ВЪВ ВАЛУТА', 'AZV-MAIN ASSEMBLY CYPRUS LTD, payment on invoice for agent servic es , GPP Ref.: 5356100577, , 1.9585, REVOLT21XXX REVOLUT BANK UAB, LT 443250095738556084, Themistokli Dervi 41, Office 101 Nicosia Cyprus/Издаване на превод във валута', 'AZV-MAIN ASSEMBLY CYPRUS LTD, PAYMENT ON INVOICE FOR AGENT SERVIC ES , GPP REF.: #, , #, REVOLT#XXX REVOLUT BANK UAB, LT #, THEMISTOKLI DERVI #, OFFICE # NICOSIA CYPRUS/IZDAVANE NA PREVOD VAV VALUTA', 16, 'mined'),
    ('PROFORM-# ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'proform-9000030236 Платежно нареждане извън банката', 'PROFORM-# PLATEZHNO NAREZHDANE IZVAN BANKATA', 16, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, SOCIALPILOT/SOCIALPILOT.C/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 30.00 USD, авт.код:252048, SOCIALPILOT/SOCIALPILOT.C/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, SOCIALPILOT/SOCIALPILOT.C/PAN:#****#/CT:# CARD TRANSACTION', 16, 'mined'),
    ('P# BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'P13585052 BLINK Платежно нареждане извън банката', 'P# BLINK PAYMENT ORDER OUTSIDE THE BANK', 14, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:896452-Dropbox/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 14, 'mined'),
    ('ПОС # USD АВТ.КОД:#-MICROSOFT-G#/MSBILL.INFO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1303.93 USD авт.код:972908-Microsoft-G112474622/msbill.info/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-MICROSOFT-G#/MSBILL.INFO/USA/PAN:#****#/CT:# CARD TRANSACTION', 14, 'mined'),
    ('ПРЕВОД ПО Ф-РА НАЕМ НА АВТОМОБИЛ CAR RENTAL ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'превод по ф-ра наем на автомобил Car rental Издаден вътр.банков превод', 'INVOICE TRANSFER CAR RENTAL CAR RENTAL INTERNAL BANK TRANSFER ISSUED', 14, 'mined'),
    ('ТАКСА БИТОВИ ОТПАДЪЦИ ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Такса Битови отпадъци Платежно нареждане извън банката', 'WASTE COLLECTION FEE PLATEZHNO NAREZHDANE IZVAN BANKATA', 14, 'mined'),
    ('ГОРИВО КОМАНДИРОВКА BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Гориво командировка BLINK Платежно нареждане извън банката', 'GORIVO KOMANDIROVKA BLINK PAYMENT ORDER OUTSIDE THE BANK', 12, 'mined'),
    ('ПЛАЩАНЕ ПО ФАКТУРА ЗА АГЕНТСКИ УСЛУГИ AGENT CONTRACT ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'плащане по фактура за агентски услуги Agent Contract Издаден вътр.банков превод', 'INVOICE PAYMENT ZA AGENTSKI USLUGI AGENT CONTRACT INTERNAL BANK TRANSFER ISSUED', 12, 'mined'),
    ('ПОС # CAD АВТ.КОД:#-PHOTOS-TAGGABLE/CHICAGO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1.40 CAD авт.код:561299-PHOTOS-TAGGABLE/CHICAGO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # CAD AUTH CODE:#-PHOTOS-TAGGABLE/CHICAGO/USA/PAN:#****#/CT:# CARD TRANSACTION', 12, 'mined'),
    ('ПРЕМИЯ BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Премия BLINK Платежно нареждане извън банката', 'PREMIYA BLINK PAYMENT ORDER OUTSIDE THE BANK', 12, 'mined'),
    ('Ф-РА # AGENT CONTRACT ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000000112 Agent Contract Издаден вътр.банков превод', 'INVOICE # AGENT CONTRACT INTERNAL BANK TRANSFER ISSUED', 12, 'mined'),
    ('Ф-РА # CAR RENTAL ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000000113 Car rental Издаден вътр.банков превод', 'INVOICE # CAR RENTAL INTERNAL BANK TRANSFER ISSUED', 12, 'mined'),
    ('ПОС # USD АВТ.КОД:#-CLICKUP /# /USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 396.00 USD авт.код:950997-CLICKUP /8886254258 /USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-CLICKUP /# /USA/PAN:#****#/CT:# CARD TRANSACTION', 11, 'mined'),
    ('АТМ # BGN АВТ.КОД:#-UNICREDIT BULBANK AD/SOFIA/TID:A#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'АТМ 110.00 BGN авт.код:557534-UNICREDIT BULBANK AD/SOFIA/TID:A5400703/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'ATM # BGN AUTH CODE:#-UNICREDIT BULBANK AD/SOFIA/TID:A#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 10, 'mined'),
    ('ЗАПЛАТА # # SALARY # # ИЗХ.ПРЕВОД SEPA В ЕИП', 'Заплата 02 2026 Salary 02 2026 Изх.превод SEPA в ЕИП', 'ZAPLATA # # SALARY # # OUTGOING SEPA TRANSFER', 10, 'mined'),
    ('ПРОФ Ф-РА # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'проф ф-ра 144494 BLINK Платежно нареждане извън банката', 'PROFORMA INVOICE # BLINK PAYMENT ORDER OUTSIDE THE BANK', 10, 'mined'),
    ('AZV-MAIN ASSEMBLY CYPRUS LTD, PAYMENT ON INVOICE FOR AGENT SERVIC ES , GPP REF.: #, , #, BCYPCY#NXXX , CY# #, THEMISTOKLI DERVI #, OFFICE # NICOSIA CYPRUS/ИЗДАВАНЕ НА ПРЕВОД ВЪВ ВАЛУТА', 'AZV-MAIN ASSEMBLY CYPRUS LTD, payment on invoice for agent servic es , GPP Ref.: 5105100721, , 1.9585, BCYPCY2NXXX , CY3600200195000035 7038446989, Themistokli Dervi 41, Office 101 Nicosia Cyprus/Издаване на превод във валута', 'AZV-MAIN ASSEMBLY CYPRUS LTD, PAYMENT ON INVOICE FOR AGENT SERVIC ES , GPP REF.: #, , #, BCYPCY#NXXX , CY# #, THEMISTOKLI DERVI #, OFFICE # NICOSIA CYPRUS/IZDAVANE NA PREVOD VAV VALUTA', 8, 'mined'),
    ('FASTPORT WORK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Fastport Work Платежно нареждане извън банката', 'FASTPORT WORK PLATEZHNO NAREZHDANE IZVAN BANKATA', 8, 'mined'),
    ('P# ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'P13585052 Платежно нареждане извън банката', 'P# PLATEZHNO NAREZHDANE IZVAN BANKATA', 8, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-ECONT EXPRESS LTD/RUSE/TID:V#/PAN:#****#/CT:#/NOM::MBDU/NP:# ОПЕРАЦИЯ С КАРТА', 'ПОС 100.00 BGN авт.код:517532-ECONT EXPRESS LTD/RUSE/TID:V5401029/PAN:5408****8235/CT:08/NOM::MBDU/NP:127622 Операция с карта', 'POS # BGN AUTH CODE:#-ECONT EXPRESS LTD/RUSE/TID:V#/PAN:#****#/CT:#/NOM::MBDU/NP:# CARD TRANSACTION', 8, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-V I HUNTING OOD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 85.70 BGN авт.код:797730-V I HUNTING OOD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-V I HUNTING OOD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 8, 'mined'),
    ('ПОС # USD АВТ.КОД:#-APR*APPRIVER/GULF BREEZE/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 335.04 USD авт.код:674691-APR*APPRIVER/GULF BREEZE/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-APR*APPRIVER/GULF BREEZE/USA/PAN:#****#/CT:# CARD TRANSACTION', 8, 'mined'),
    ('ПОС # USD АВТ.КОД:#-OPENAI/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 81.00 USD авт.код:428650-OPENAI/SAN FRANCISCO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-OPENAI/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 8, 'mined'),
    ('ПРЕМИЯ ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Премия Платежно нареждане извън банката', 'PREMIYA PLATEZHNO NAREZHDANE IZVAN BANKATA', 8, 'mined'),
    ('ПОС # USD АВТ.КОД:#-MICROSOFT-G#/REDMOND/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1251.62 USD авт.код:537724-Microsoft-G145720617/Redmond/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-MICROSOFT-G#/REDMOND/USA/PAN:#****#/CT:# CARD TRANSACTION', 7, 'mined'),
    ('ПРОФ Ф-РА # ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'проф ф-ра 9000034174 Издаден вътр.банков превод', 'PROFORMA INVOICE # INTERNAL BANK TRANSFER ISSUED', 7, 'mined'),
    ('BONUS BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Bonus BLINK Платежно нареждане извън банката', 'BONUS BLINK PAYMENT ORDER OUTSIDE THE BANK', 6, 'mined'),
    ('BONUS БОНУС ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Bonus Бонус Издаден вътр.банков превод', 'BONUS BONUS INTERNAL BANK TRANSFER ISSUED', 6, 'mined'),
    ('FASTPORT WORK BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Fastport Work BLINK Платежно нареждане извън банката', 'FASTPORT WORK BLINK PAYMENT ORDER OUTSIDE THE BANK', 6, 'mined'),
    ('PROFORM-# BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'proform-9000030565 BLINK Платежно нареждане извън банката', 'PROFORM-# BLINK PAYMENT ORDER OUTSIDE THE BANK', 6, 'mined'),
    ('БОНУС BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Бонус BLINK Платежно нареждане извън банката', 'BONUS BLINK PAYMENT ORDER OUTSIDE THE BANK', 6, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-T-S MALLPARADISE/SOFIYA/TID:P#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'ПОС 6.99 BGN авт.код:425025-T-S MALLPARADISE/SOFIYA/TID:P5428529/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'POS # BGN AUTH CODE:#-T-S MALLPARADISE/SOFIYA/TID:P#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 6, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-AWS EMEA/AWS.AMAZON.CO/LUX/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 5.82 EUR авт.код:911988-AWS EMEA/aws.amazon.co/LUX/PAN:5408****6583/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-AWS EMEA/AWS.AMAZON.CO/LUX/PAN:#****#/CT:# CARD TRANSACTION', 6, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-INTUIT *QBOOKS ONLINE/SAN DIEGO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 31.00 EUR авт.код:919602-INTUIT *QBooks Online/SAN DIEGO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-INTUIT *QBOOKS ONLINE/SAN DIEGO/USA/PAN:#****#/CT:# CARD TRANSACTION', 6, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:054514, Dropbox/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 6, 'mined'),
    ('ПОС # USD АВТ.КОД:#-FIGMA MONTHLY RENEWAL/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 18.00 USD авт.код:514533-FIGMA MONTHLY RENEWAL/SAN FRANCISCO/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-FIGMA MONTHLY RENEWAL/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 6, 'mined'),
    ('ПРОФОРМА ФАКТУРА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Проформа фактура 0000013819 Платежно нареждане извън банката', 'PROFORMA FAKTURA # PLATEZHNO NAREZHDANE IZVAN BANKATA', 6, 'mined'),
    ('Ф-РA # MULTISPORT ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-рa 2000318300 Multisport Издаден вътр.банков превод', 'F-RA # MULTISPORT INTERNAL BANK TRANSFER ISSUED', 6, 'mined'),
    ('P# ИЗХ.ПРЕВОД SEPA В ЕИП', 'P13585052 Изх.превод SEPA в ЕИП', 'P# OUTGOING SEPA TRANSFER', 5, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, DNH*GODADDY##/#-#/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 289.98 USD, авт.код:407749, DNH*GODADDY#3995449238/480-5058855/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, DNH*GODADDY##/#-#/PAN:#****#/CT:# CARD TRANSACTION', 5, 'mined'),
    ('BONUS # # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Bonus 09 2025 BLINK Платежно нареждане извън банката', 'BONUS # # BLINK PAYMENT ORDER OUTSIDE THE BANK', 4, 'mined'),
    ('EHS # #/# .#/# КОМУНАЛНО ПЛАЩАНЕ BBO', 'EHS 210044998247 430039197005/10.11 .2025/10.11.2025 Комунално плащане BBO', 'EHS # #/# .#/# UTILITY PAYMENT BBO', 4, 'mined'),
    ('FASTPORT+SALESFORCE WORK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Fastport+Salesforce Work Платежно нареждане извън банката', 'FASTPORT+SALESFORCE WORK PLATEZHNO NAREZHDANE IZVAN BANKATA', 4, 'mined'),
    ('SALARY # # ЗАПЛАТА ЗА М # # ИЗХ.ПРЕВОД SEPA В ЕИП', 'Salary 02 2026 заплата за м 02 2026 Изх.превод SEPA в ЕИП', 'SALARY # # SALARY ZA M # # OUTGOING SEPA TRANSFER', 4, 'mined'),
    ('АВ ДАНЪК ГРАЖДАНСКИ ДОГОВОРИ ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Ав данък граждански договори Платежно нареждане извън банката', 'AV DANAK GRAZHDANSKI DOGOVORI PLATEZHNO NAREZHDANE IZVAN BANKATA', 4, 'mined'),
    ('БОНУС ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Бонус Платежно нареждане извън банката', 'BONUS PLATEZHNO NAREZHDANE IZVAN BANKATA', 4, 'mined'),
    ('НОМЕР НА ПОРЪЧКА # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Номер на поръчка 8369 BLINK Платежно нареждане извън банката', 'NOMER NA PORACHKA # BLINK PAYMENT ORDER OUTSIDE THE BANK', 4, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-INTERNET KAFE BG LTD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 61.65 BGN авт.код:344474-INTERNET KAFE BG LTD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-INTERNET KAFE BG LTD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-IKEA BULGARIA /SOFIA /BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 363.00 BGN авт.код:813496-IKEA BULGARIA /Sofia /BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-IKEA BULGARIA /SOFIA /BGR/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-TAKEAWAY.COM/BG/SOFIA/BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 239.92 BGN авт.код:695362-takeaway.com/bg/Sofia/BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-TAKEAWAY.COM/BG/SOFIA/BGR/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-AWS EMEA/LUXEMBOURG/LUX/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 0.26 EUR авт.код:826325-AWS EMEA/LUXEMBOURG/LUX/PAN:5408****6583/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-AWS EMEA/LUXEMBOURG/LUX/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-S PLYUS S-S. TIMEVA EOO/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 33.18 EUR авт.код:771782-S PLYUS S-S. TIMEVA EOO/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-S PLYUS S-S. TIMEVA EOO/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # GBP АВТ.КОД:#-DNH*GODADDY##/HAYES/GBR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 479.96 GBP авт.код:098287-DNH*GODADDY#3958669277/HAYES/GBR/PAN:5408****6583/CT:08 Операция с карта', 'POS # GBP AUTH CODE:#-DNH*GODADDY##/HAYES/GBR/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # USD АВТ.КОД:#-APPLE.COM/US/#-#-#/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 2188.91 USD авт.код:138921-APPLE.COM/US/800-676-2775/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-APPLE.COM/US/#-#-#/USA/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # USD АВТ.КОД:#-BROWSERSTACK.COM/LEWES/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 348.00 USD авт.код:980567-BROWSERSTACK.COM/LEWES/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-BROWSERSTACK.COM/LEWES/USA/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПОС # USD АВТ.КОД:#-MICROSOFT#G#/REDMOND/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1336.35 USD авт.код:209523-MICROSOFT#G128233555/REDMOND/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-MICROSOFT#G#/REDMOND/USA/PAN:#****#/CT:# CARD TRANSACTION', 4, 'mined'),
    ('ПРЕМИЯ BONUS ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Премия Bonus Издаден вътр.банков превод', 'PREMIYA BONUS INTERNAL BANK TRANSFER ISSUED', 4, 'mined'),
    ('ПРОФ Ф-РА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'проф ф-ра 0100004095 Платежно нареждане извън банката', 'PROFORMA INVOICE # PLATEZHNO NAREZHDANE IZVAN BANKATA', 4, 'mined'),
    ('AZV-COMMISSION # EUR FOR GPP TRANSACTION REF.: #/ТАКСИ ПОЛУЧЕНИ ВАЛУТНИ ПРЕВОДИ', 'AZV-Commission 53360.00 EUR for GPP transaction Ref.: 6029201013/Такси получени валутни преводи', 'AZV-COMMISSION # EUR FOR GPP TRANSACTION REF.: #/FEES FOR RECEIVED FOREIGN CURRENCY TRANSFERS', 3, 'mined'),
    ('FASTPORT WORK ПЛАЩАНЕ ПО Ф-РА # ИЗХ.ПРЕВОД SEPA В ЕИП', 'Fastport Work Плащане по ф-ра 179 Изх.превод SEPA в ЕИП', 'FASTPORT WORK PLASHTANE PO INVOICE # OUTGOING SEPA TRANSFER', 3, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # EUR АВТ.КОД:#-A# BULGARIA LTD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 161.20 EUR авт.код:305309-A1 BULGARIA LTD/Sofia/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # EUR AUTH CODE:#-A# BULGARIA LTD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 3, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-KAFFEKAPSLEN/HASSELAGER/DNK/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 63.96 EUR авт.код:772659-KaffeKapslen/Hasselager/DNK/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-KAFFEKAPSLEN/HASSELAGER/DNK/PAN:#****#/CT:# CARD TRANSACTION', 3, 'mined'),
    ('ПОС # USD АВТ.КОД:#-HIGHLEVEL INC./DALLAS/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 10.00 USD авт.код:756638-HIGHLEVEL INC./DALLAS/USA/PAN:5408****6583/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-HIGHLEVEL INC./DALLAS/USA/PAN:#****#/CT:# CARD TRANSACTION', 3, 'mined'),
    ('ПОС # USD АВТ.КОД:#-RELUME.IO/DURAL/AUS/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 480.00 USD авт.код:210824-RELUME.IO/DURAL/AUS/PAN:5408****6583/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-RELUME.IO/DURAL/AUS/PAN:#****#/CT:# CARD TRANSACTION', 3, 'mined'),
    ('#;# ДЪ БИ ТИЙМ ООД ЗАСТРАХОВАТЕЛНА ПРЕМИЯ', '3000203001542;203913310 ДЪ БИ ТИЙМ ООД Застрахователна премия', '#;# DA BI TIYM OOD ZASTRAHOVATELNA PREMIYA', 2, 'mined'),
    ('ANNUAL MAINT # FIRE EXTINGUISHER ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'annual maint 4 fire extinguisher Платежно нареждане извън банката', 'ANNUAL MAINT # FIRE EXTINGUISHER PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('AZV-ATANAS MARINOV, SALARY # # , GPP REF.: #, , , REVOLT# REVOLUT BANK UAB, LT#, SOFIA, HADJI DIMITAR # #A FL.# AP.# SOFIA BULGARIA/ИЗДАВАНЕ НА ПРЕВОД ВЪВ ВАЛУТА', 'AZV-Atanas Marinov, salary 07 2025 , GPP Ref.: 5216100770, , , REVOLT21 REVOLUT BANK UAB, LT493250001805015054, Sofia, Hadji Dimitar 5 7A fl.2 ap.8 Sofia Bulgaria/Издаване на превод във валута', 'AZV-ATANAS MARINOV, SALARY # # , GPP REF.: #, , , REVOLT# REVOLUT BANK UAB, LT#, SOFIA, HADJI DIMITAR # #A FL.# AP.# SOFIA BULGARIA/IZDAVANE NA PREVOD VAV VALUTA', 2, 'mined'),
    ('AZV-COMMUNICATION FEE FOR INTERNATIONAL TRANSACTION REF.: #/ТАКСИ ИЗДАДЕНИ ВАЛУТНИ ПРЕВОДИ', 'AZV-Communication fee for international transaction Ref.: 5216100770/Такси издадени валутни преводи', 'AZV-COMMUNICATION FEE FOR INTERNATIONAL TRANSACTION REF.: #/FEES FOR OUTGOING FOREIGN CURRENCY TRANSFERS', 2, 'mined'),
    ('AZV-MAIN ASSEMBLY CYPRUS LTD, PAYMENT ON INVOICE FOR AGENT SERVIC ES , GPP REF.: #, , , REVOLT#XXX REVOLUT BANK UAB, LT# #, THEMISTOKLI DERVI #, OFFICE # NICOSIA CYPRUS/ИЗДАВАНЕ НА ПРЕВОД ВЪВ ВАЛУТА', 'AZV-MAIN ASSEMBLY CYPRUS LTD, payment on invoice for agent servic es , GPP Ref.: 6058100878, , , REVOLT21XXX REVOLUT BANK UAB, LT443250 095738556084, Themistokli Dervi 41, Office 101 Nicosia Cyprus/Издаване на превод във валута', 'AZV-MAIN ASSEMBLY CYPRUS LTD, PAYMENT ON INVOICE FOR AGENT SERVIC ES , GPP REF.: #, , , REVOLT#XXX REVOLUT BANK UAB, LT# #, THEMISTOKLI DERVI #, OFFICE # NICOSIA CYPRUS/IZDAVANE NA PREVOD VAV VALUTA', 2, 'mined'),
    ('BONUS # # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Bonus 10 2025 Платежно нареждане извън банката', 'BONUS # # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('COMPANY ANNIVERSARY CAKE BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Company Anniversary cake BLINK Платежно нареждане извън банката', 'COMPANY ANNIVERSARY CAKE BLINK PAYMENT ORDER OUTSIDE THE BANK', 2, 'mined'),
    ('COMPANY XMASS CAKE BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Company Xmass cake BLINK Платежно нареждане извън банката', 'COMPANY XMASS CAKE BLINK PAYMENT ORDER OUTSIDE THE BANK', 2, 'mined'),
    ('CONTRACTOR AGREEMENT # # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Contractor Agreement 06 2025 Платежно нареждане извън банката', 'CONTRACTOR AGREEMENT # # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('DEPOSIT HOTEL TEAM BUILDING ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Deposit hotel team building Платежно нареждане извън банката', 'DEPOSIT HOTEL TEAM BUILDING PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('FASTPORT+SALESFORCE NOV # WORK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Fastport+Salesforce Nov 2024 Work Платежно нареждане извън банката', 'FASTPORT+SALESFORCE NOV # WORK PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('FASTPORT+SALESFORCE OCT # WORK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Fastport+Salesforce Oct 2024 Work Платежно нареждане извън банката', 'FASTPORT+SALESFORCE OCT # WORK PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('FASTPORT+SALESFORCE WORK BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Fastport+Salesforce Work BLINK Платежно нареждане извън банката', 'FASTPORT+SALESFORCE WORK BLINK PAYMENT ORDER OUTSIDE THE BANK', 2, 'mined'),
    ('FEE КРЕДИТ ПОС # BGN АВТ.КОД:#-FUNIDELIA/ZARAGOZA/ESP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Fee Кредит ПОС 27.35 BGN авт.код:909155-FUNIDELIA/ZARAGOZA/ESP/PAN:5408****8235/CT:08 Операция с карта', 'FEE KREDIT POS # BGN AUTH CODE:#-FUNIDELIA/ZARAGOZA/ESP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('FEE КРЕДИТ ПОС # EUR АВТ.КОД:-CLAUDE.AI SUBSCRIPTION/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Fee Кредит ПОС 3.60 EUR авт.код:-CLAUDE.AI SUBSCRIPTION/SAN FRANCISCO/USA/PAN:5408****6583/CT:08 Операция с карта', 'FEE KREDIT POS # EUR AUTH CODE:-CLAUDE.AI SUBSCRIPTION/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('FEE КРЕДИТ ПОС # USD АВТ.КОД:-BROWSERSTACK.COM/LEWES/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Fee Кредит ПОС 348.00 USD авт.код:-BROWSERSTACK.COM/LEWES/USA/PAN:5408****8235/CT:08 Операция с карта', 'FEE KREDIT POS # USD AUTH CODE:-BROWSERSTACK.COM/LEWES/USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('FEE КРЕДИТ ПОС # USD, АВТ.КОД:#, CLUTCH.CO/WASHINGTON/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Fee Кредит ПОС 1500.00 USD, авт.код:033483, CLUTCH.CO/WASHINGTON/PAN:4106****4666/CT:01 Операция с карта', 'FEE KREDIT POS # USD, AUTH CODE:#, CLUTCH.CO/WASHINGTON/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('HVACS ANNUAL MAINTENANCE КЛИМ ПРОФИЛАКТИКА Ф-РА # ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'hvacs annual maintenance клим профилактика ф-ра 0000070785 Издаден вътр.банков превод', 'HVACS ANNUAL MAINTENANCE KLIM PROFILAKTIKA INVOICE # INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('WORKPLACE ENVIRONMENT ASSESSMENT EVERY # YRS ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'workplace environment assessment every 5 yrs Платежно нареждане извън банката', 'WORKPLACE ENVIRONMENT ASSESSMENT EVERY # YRS PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('WORKPLACE REQUIREMENTS ANNUAL BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'workplace requirements annual BLINK Платежно нареждане извън банката', 'WORKPLACE REQUIREMENTS ANNUAL BLINK PAYMENT ORDER OUTSIDE THE BANK', 2, 'mined'),
    ('АТМ # BGN АВТ.КОД:#-UBB N.VAPTSAROV #,EXPO/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'АТМ 100.00 BGN авт.код:735557-UBB N.VAPTSAROV 55,EXPO/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'ATM # BGN AUTH CODE:#-UBB N.VAPTSAROV #,EXPO/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('БОНУС BONUS ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Бонус Bonus Издаден вътр.банков превод', 'BONUS BONUS INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ВНОС ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Внос Платежно нареждане извън банката', 'VNOS PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ВНОСКИ ЗА ДЗПО ИЗХ.ПРЕВОД SEPA В ЕИП', 'Вноски за ДЗПО Изх.превод SEPA в ЕИП', 'SUPPLEMENTARY PENSION CONTRIBUTIONS OUTGOING SEPA TRANSFER', 2, 'mined'),
    ('ВНОСКИ ЗА ДОО ИЗХ.ПРЕВОД SEPA В ЕИП', 'Вноски за ДОО Изх.превод SEPA в ЕИП', 'SOCIAL SECURITY CONTRIBUTIONS OUTGOING SEPA TRANSFER', 2, 'mined'),
    ('ВНОСКИ ЗА ЗО ИЗХ.ПРЕВОД SEPA В ЕИП', 'Вноски за ЗО Изх.превод SEPA в ЕИП', 'HEALTH INSURANCE CONTRIBUTIONS OUTGOING SEPA TRANSFER', 2, 'mined'),
    ('ДАНЪК ВЪРХУ НЕДВИЖИМИ ИМОТИ ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Данък върху недвижими имоти Платежно нареждане извън банката', 'DANAK VARHU NEDVIZHIMI IMOTI PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ДАНЪК ПЕЧАЛБА АВАНСОВ ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Данък печалба авансов Платежно нареждане извън банката', 'DANAK PECHALBA AVANSOV PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ДОГОВОР # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'договор 888634 Платежно нареждане извън банката', 'DOGOVOR # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ДОД ИЗХ.ПРЕВОД SEPA В ЕИП', 'ДОД Изх.превод SEPA в ЕИП', 'WITHHOLDING INCOME TAX OUTGOING SEPA TRANSFER', 2, 'mined'),
    ('ДОКУМЕНТ ЗА ПРОДАЖБА E# ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'документ за продажба E12532 Платежно нареждане извън банката', 'DOKUMENT ZA PRODAZHBA E# PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ДПР, ДСР ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ДПР, ДСР Платежно нареждане извън банката', 'DPR, DSR PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ЗАЯВКА OK-# B-TRUST SIGNATURE ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'Заявка OK-500305731 B-trust signature Издаден вътр.банков превод', 'ZAYAVKA OK-# B-TRUST SIGNATURE INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ЗДДФЛ ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ЗДДФЛ Платежно нареждане извън банката', 'ZDDFL PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('НОМЕР НА ПОРЪЧКА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Номер на поръчка 8583 Платежно нареждане извън банката', 'NOMER NA PORACHKA # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-BAR PETAK LTD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 227.50 BGN авт.код:597972-BAR PETAK LTD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-BAR PETAK LTD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-ELEKTROHOLD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 438.96 BGN авт.код:309597-ELEKTROHOLD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-ELEKTROHOLD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-HIPPOLAND AD/KAZICHENE/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 19.98 BGN авт.код:417661-HIPPOLAND AD/Kazichene/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-HIPPOLAND AD/KAZICHENE/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-JUMBO/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 49.42 BGN авт.код:387722-JUMBO/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-JUMBO/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-NOTARIUS ANGELOVA #/PLOVDIV/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 6.00 BGN авт.код:093431-NOTARIUS ANGELOVA 789/PLOVDIV/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-NOTARIUS ANGELOVA #/PLOVDIV/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-OZONE.BG/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 402.88 BGN авт.код:312598-OZONE.BG/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-OZONE.BG/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # BGN АВТ.КОД:#-PASTA DUE LTD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 254.80 BGN авт.код:904220-PASTA DUE LTD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # BGN AUTH CODE:#-PASTA DUE LTD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # EUR АВТ.КОД:#-EPAY OFFICE#.BG/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 61.89 EUR авт.код:557497-ePay office1.bg/Sofia/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # EUR AUTH CODE:#-EPAY OFFICE#.BG/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # EUR АВТ.КОД:#-SUPERHOSTING.BG BGN/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 39.21 EUR авт.код:411598-SUPERHOSTING.BG BGN/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # EUR AUTH CODE:#-SUPERHOSTING.BG BGN/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОГАСЯВ.НА Л-ВА ЗА РЕДОВНА ГЛАВНИЦА # EUR # ПОГАСЯВ.НА Л-ВА ЗА РЕДОВНА ГЛАВНИЦА', 'Погасяв.на л-ва за редовна главница 70001522532201 EUR 246.19 Погасяв.на л-ва за редовна главница', 'LOAN INTEREST REPAYMENT # EUR # LOAN INTEREST REPAYMENT', 2, 'mined'),
    ('ПОГАСЯВАНЕ НА ГЛАВНИЦА # EUR # ПОГАСЯВАНЕ НА ГЛАВНИЦА', 'Погасяване на главница 70001522532201 EUR 2118.79 Погасяване на главница', 'LOAN PRINCIPAL REPAYMENT # EUR # LOAN PRINCIPAL REPAYMENT', 2, 'mined'),
    ('ПОРЪЧКА ESH# OFFICE COFFEE ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'поръчка ESH0048112 office coffee Издаден вътр.банков превод', 'PORACHKA ESH# OFFICE COFFEE INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-BURGERJOINT#.COM/SOFIA/BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 396.82 BGN авт.код:636693-BURGERJOINT2020.COM/SOFIA/BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-BURGERJOINT#.COM/SOFIA/BGR/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-CHERNI VRAH/NO DATA/TID:#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'ПОС 8.90 BGN авт.код:899347-CHERNI VRAH/NO DATA/TID:93927419/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'POS # BGN AUTH CODE:#-CHERNI VRAH/NO DATA/TID:#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-DOBRA HRANA OOD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 247.80 BGN авт.код:294368-DOBRA HRANA OOD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-DOBRA HRANA OOD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-DOSTAVKA.HAPPY.BG/VARNA/BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 197.82 BGN авт.код:509630-dostavka.happy.bg/Varna/BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-DOSTAVKA.HAPPY.BG/VARNA/BGR/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-FUNIDELIA/ZARAGOZA/ESP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 27.35 BGN авт.код:587846-FUNIDELIA/ZARAGOZA/ESP/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-FUNIDELIA/ZARAGOZA/ESP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-JOVAN LTD/SOFIA/TID:P#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'ПОС 234.00 BGN авт.код:442956-JOVAN LTD/SOFIA/TID:P5431252/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'POS # BGN AUTH CODE:#-JOVAN LTD/SOFIA/TID:P#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-ROYAL PLEYS OOD/SOFIYA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1292.60 BGN авт.код:564049-ROYAL PLEYS OOD/SOFIYA/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-ROYAL PLEYS OOD/SOFIYA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-SOFIA-PANTELEEV/RUSE/TID:#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'ПОС 6.22 BGN авт.код:276106-SOFIA-PANTELEEV/RUSE/TID:93905057/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'POS # BGN AUTH CODE:#-SOFIA-PANTELEEV/RUSE/TID:#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-SOT-SIGNALNO OHRANITELNA/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 674.09 BGN авт.код:560307-SOT-SIGNALNO OHRANITELNA/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-SOT-SIGNALNO OHRANITELNA/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-SPEEDY MPOS #/# SOFIYA/TID:P#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'ПОС 120.54 BGN авт.код:976544-SPEEDY MPOS 424/1138 SOFIYA/TID:P5425435/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'POS # BGN AUTH CODE:#-SPEEDY MPOS #/# SOFIYA/TID:P#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 2, 'mined'),
    ('ПОС # BGN АВТ.КОД:#-WWW.ZOYA.BG/SOFIYA/BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 69.65 BGN авт.код:148307-www.zoya.bg/Sofiya/BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # BGN AUTH CODE:#-WWW.ZOYA.BG/SOFIYA/BGR/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#CTPN#ZMY/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:962906-Dropbox*44CTPN732ZMY/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#CTPN#ZMY/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#FK#B#XF/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:828949-Dropbox*77FK5B3998XF/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#FK#B#XF/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#FND#SXKW/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:593424-Dropbox*91FND589SXKW/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#FND#SXKW/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#K#LZV#LDK#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:970524-Dropbox*2K6LZV4LDK81/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#K#LZV#LDK#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#L#D#N#TH/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:697824-Dropbox*7L462D8N84TH/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#L#D#N#TH/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#L#HZKC#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:087543-Dropbox*9L7964HZKC89/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#L#HZKC#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#N#GYM#HBPDD/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:314241-Dropbox*7N6GYM1HBPDD/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#N#GYM#HBPDD/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*BBMBQGVTVBWV/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:164351-Dropbox*BBMBQGVTVBWV/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*BBMBQGVTVBWV/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*CSF#GNLSB#Y/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:851701-Dropbox*CSF9GNLSB92Y/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*CSF#GNLSB#Y/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*D#Y#ZQBXSK#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:905423-Dropbox*D17Y7ZQBXSK5/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*D#Y#ZQBXSK#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*H#DDRM#Y#P#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:864053-Dropbox*H2DDRM6Y74P8/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*H#DDRM#Y#P#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*JKG#PN#S#X#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:020576-Dropbox*JKG32PN2S7X6/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*JKG#PN#S#X#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*LV#DZFC#H#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:777218-Dropbox*LV71DZFC7H16/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*LV#DZFC#H#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*MVQ#N#R#H#G/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:899781-Dropbox*MVQ1N3R19H4G/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*MVQ#N#R#H#G/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*N#N#BTRMT#T/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:318865-Dropbox*N9N97BTRMT3T/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*N#N#BTRMT#T/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*VXV#VD#H#H/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:147895-Dropbox*VXV7VD69H81H/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*VXV#VD#H#H/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*XC#P#Q#VHV/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:868125-Dropbox*XC2P789Q2VHV/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*XC#P#Q#VHV/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-FC* FREEPIK PREMIUM YE/MALAGA/ESP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 120.00 EUR авт.код:631991-FC* FREEPIK PREMIUM YE/MALAGA/ESP/PAN:5408****6583/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-FC* FREEPIK PREMIUM YE/MALAGA/ESP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-FIGMA MONTHLY RENEWAL/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 30.00 EUR авт.код:799456-FIGMA MONTHLY RENEWAL/SAN FRANCISCO/USA/PAN:5408****6583/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-FIGMA MONTHLY RENEWAL/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-INVEST - BG EOOD/HASKOVO/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 25.31 EUR авт.код:876756-INVEST - BG EOOD/HASKOVO/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-INVEST - BG EOOD/HASKOVO/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-ISTYLE.BG/SOFIA/BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 965.83 EUR авт.код:698924-ISTYLE.BG/SOFIA/BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-ISTYLE.BG/SOFIA/BGR/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-ROYALCDKEYS.COM/TSIM SHA TSUI/HKG/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 4.50 EUR авт.код:156825-ROYALCDKEYS.COM/TSIM SHA TSUI/HKG/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-ROYALCDKEYS.COM/TSIM SHA TSUI/HKG/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-WP ENGINE/AUSTIN/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 320.00 EUR авт.код:404075-WP ENGINE/AUSTIN/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-WP ENGINE/AUSTIN/USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, ADOBE SYSTEMS SOFTWARE IR/SAGGART, DUBL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 645.24 EUR, авт.код:860909, Adobe Systems Software Ir/Saggart, Dubl/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, ADOBE SYSTEMS SOFTWARE IR/SAGGART, DUBL/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*#LXG#R#VN#Q/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:687551, Dropbox*85LXG4R6VN8Q/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*#LXG#R#VN#Q/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*#WMP#V#K/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:343989, Dropbox*151WMP267V1K/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*#WMP#V#K/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*#XYYCLN#W#F/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:233356, Dropbox*5XYYCLN86W1F/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*#XYYCLN#W#F/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*#YPL#VNXYG/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:069133, Dropbox*195YPL8VNXYG/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*#YPL#VNXYG/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*FCRH#W#L#TY/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:679397, Dropbox*FCRH7W37L8TY/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*FCRH#W#L#TY/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*H#JXYJCLZD#/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:647354, Dropbox*H24JXYJCLZD8/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*H#JXYJCLZD#/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*HVNFS#HLXS#/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:079799, Dropbox*HVNFS5HLXS24/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*HVNFS#HLXS#/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*T#V#F#PZKBG/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:450810, Dropbox*T9V1F26PZKBG/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*T#V#F#PZKBG/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*W#N#F#MD#WWM/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:778928, Dropbox*W1N1F2MD5WWM/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*W#N#F#MD#WWM/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, STORY BLOCKS*VIDEO/STORYBLOCKS/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 360.00 EUR, авт.код:092905, STORY BLOCKS*VIDEO/STORYBLOCKS/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, STORY BLOCKS*VIDEO/STORYBLOCKS/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD АВТ.КОД:#-ANTHROPIC/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 30.00 USD авт.код:855436-ANTHROPIC/SAN FRANCISCO/USA/PAN:5408****6583/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-ANTHROPIC/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD АВТ.КОД:#-AWS EMEA/AWS.AMAZON.CO/LUX/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 0.19 USD авт.код:727399-AWS EMEA/aws.amazon.co/LUX/PAN:5408****6583/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-AWS EMEA/AWS.AMAZON.CO/LUX/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD АВТ.КОД:#-ENVATO *# /# /USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 72.00 USD авт.код:319400-ENVATO *70355553 /61383766284 /USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-ENVATO *# /# /USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD АВТ.КОД:#-MICROSOFT#G# /MSBILL.INFO /USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1922.22 USD авт.код:915709-MICROSOFT#G077679430 /MSBILL.INFO /USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-MICROSOFT#G# /MSBILL.INFO /USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD АВТ.КОД:#-WP ENGINE/AUSTIN/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 300.00 USD авт.код:537457-WP ENGINE/AUSTIN/USA/PAN:5408****8235/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-WP ENGINE/AUSTIN/USA/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, CLUTCH.CO/CLUTCH.CO/ADV/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 1500.00 USD, авт.код:255807, CLUTCH.CO/CLUTCH.CO/ADV/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, CLUTCH.CO/CLUTCH.CO/ADV/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, OPENAI *CHATGPT SUBSCR/HTTPSOPENAI.C/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 20.00 USD, авт.код:767857, OPENAI *CHATGPT SUBSCR/HTTPSOPENAI.C/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, OPENAI *CHATGPT SUBSCR/HTTPSOPENAI.C/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПОС # USD, АВТ.КОД:#, SOCIALPILOT/HTTPSSOCIALPI/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 30.00 USD, авт.код:196116, SOCIALPILOT/HTTPSSOCIALPI/PAN:4106****4666/CT:01 Операция с карта', 'POS # USD, AUTH CODE:#, SOCIALPILOT/HTTPSSOCIALPI/PAN:#****#/CT:# CARD TRANSACTION', 2, 'mined'),
    ('ПРЕВОД ПО Ф-РА # # Г LUNCH AND LEARN LUNCH ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'превод по ф-ра 0000000645 05.07.2024 г lunch and learn lunch Издаден вътр.банков превод', 'INVOICE TRANSFER # # G LUNCH AND LEARN LUNCH INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ПРОФ Ф-РА # # WATER DISPENSER ANNUAL MAINTENANCE FEE ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'проф ф-ра 9000032057 2 Water dispenser annual maintenance fee Издаден вътр.банков превод', 'PROFORMA INVOICE # # WATER DISPENSER ANNUAL MAINTENANCE FEE INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ПРОФ Ф-РА # MENS TOILET BUTTON ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'проф ф-ра 20000000000000017990 Mens Toilet button Издаден вътр.банков превод', 'PROFORMA INVOICE # MENS TOILET BUTTON INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ПРОФ Ф-РА # WATER DISPENSERS CLEAN UP ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'проф ф-ра 9000030924 Water Dispensers Clean Up Издаден вътр.банков превод', 'PROFORMA INVOICE # WATER DISPENSERS CLEAN UP INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ПРОФ Ф-РА SF#NSO# ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'проф ф-ра SF01NSO1300112 Платежно нареждане извън банката', 'PROFORMA INVOICE SF#NSO# PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ПРОФ Ф-РА ППШ-# ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'проф ф-ра ППШ-521712 Платежно нареждане извън банката', 'PROFORMA INVOICE PPSH-# PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ПРОФОРМА Ф-РА # MATT S COMPUTER ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'проформа ф-ра 0000119133 Matt s computer Издаден вътр.банков превод', 'PROFORMA INVOICE # MATT S COMPUTER INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ПРОФОРМА Ф-РА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Проформа ф-ра 10017001 Платежно нареждане извън банката', 'PROFORMA INVOICE # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ПРОФОРМА Ф-РА ЗА ПОРЪЧКА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'проформа ф-ра за поръчка 7597 Платежно нареждане извън банката', 'PROFORMA INVOICE ZA PORACHKA # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ПРОФОРМА ФАКТУРА # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Проформа Фактура 0000616806 BLINK Платежно нареждане извън банката', 'PROFORMA FAKTURA # BLINK PAYMENT ORDER OUTSIDE THE BANK', 2, 'mined'),
    ('ТАКСА БИТОВИ ОТПАДЪЦИ ИЗХ.ПРЕВОД SEPA В ЕИП', 'Такса Битови отпадъци Изх.превод SEPA в ЕИП', 'WASTE COLLECTION FEE OUTGOING SEPA TRANSFER', 2, 'mined'),
    ('Ф-РА # OFFICE AC MAINTENANCE ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000082665 Office AC maintenance Издаден вътр.банков превод', 'INVOICE # OFFICE AC MAINTENANCE INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('Ф-РА # OFFICE AC REPAIR ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000083382 Office AC repair Издаден вътр.банков превод', 'INVOICE # OFFICE AC REPAIR INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('Ф-РА # RECRUITMENT COMISSION LARAVEL DEV ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000001315 Recruitment comission Laravel Dev Издаден вътр.банков превод', 'INVOICE # RECRUITMENT COMISSION LARAVEL DEV INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('Ф-РА # RECRUITMENT COMISSION PM ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000001331 Recruitment comission PM Издаден вътр.банков превод', 'INVOICE # RECRUITMENT COMISSION PM INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('Ф-РА # RECRUITMENT COMISSION WORDPRESS DEV ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000001291 Recruitment comission Wordpress Dev Издаден вътр.банков превод', 'INVOICE # RECRUITMENT COMISSION WORDPRESS DEV INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('Ф-РА # XMASS PARTY DECORATIONS ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 1000001083 Xmass party decorations Издаден вътр.банков превод', 'INVOICE # XMASS PARTY DECORATIONS INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('Ф-РА # XMASS ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000000035 Xmass Издаден вътр.банков превод', 'INVOICE # XMASS INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ФАКТУРА # CHRISTMAS PARTY CLUB DOWNPAYMENT ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'фактура 0000000326 Christmas party club downpayment Издаден вътр.банков превод', 'FAKTURA # CHRISTMAS PARTY CLUB DOWNPAYMENT INTERNAL BANK TRANSFER ISSUED', 2, 'mined'),
    ('ФАКТУРА # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'фактура 0000000045 Платежно нареждане извън банката', 'FAKTURA # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('ФАКТУРА NO # ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Фактура No 0100000329 Платежно нареждане извън банката', 'FAKTURA NO # PLATEZHNO NAREZHDANE IZVAN BANKATA', 2, 'mined'),
    ('SALARY # # ЗАПЛАТА # # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Salary 02 2026 заплата 02 2026 BLINK Платежно нареждане извън банката', 'SALARY # # SALARY # # BLINK PAYMENT ORDER OUTSIDE THE BANK', 1, 'mined'),
    ('SALARY # # ЗАПЛАТА ЗА М # # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'Salary 01 2026 заплата за м 01 2026 BLINK Платежно нареждане извън банката', 'SALARY # # SALARY ZA M # # BLINK PAYMENT ORDER OUTSIDE THE BANK', 1, 'mined'),
    ('НОМЕР НА ПОРЪЧКА # PAPER TOWELS ИЗХ.ПРЕВОД SEPA В ЕИП', 'Номер на поръчка 8763 Paper Towels Изх.превод SEPA в ЕИП', 'NOMER NA PORACHKA # PAPER TOWELS OUTGOING SEPA TRANSFER', 1, 'mined'),
    ('ПЛАЩАНЕ /ИМПРИНТЕР/ # EUR АВТ.КОД:#-BORICA AD/SOFIA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'Плащане /импринтер/ 24.54 EUR авт.код:190162-BORICA AD/SOFIA/PAN:5408****8235/CT:08 Операция с карта', 'CARD PAYMENT / IMPRINTER / # EUR AUTH CODE:#-BORICA AD/SOFIA/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*#N#VFZLNNDFV/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:351103-Dropbox*3N2VFZLNNDFV/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*#N#VFZLNNDFV/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*C#B#GZ#DQZ#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:034570-Dropbox*C2B6GZ32DQZ9/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*C#B#GZ#DQZ#/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*CQVNVTSF#B#L/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 43.50 EUR авт.код:533802-Dropbox*CQVNVTSF5B4L/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*CQVNVTSF#B#L/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*FHGWH#J#WQVG/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:077851-Dropbox*FHGWH1J4WQVG/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*FHGWH#J#WQVG/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-DROPBOX*KN#LZ#VXBHZN/DB.TT/CCHELP/IRL/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 11.99 EUR авт.код:616479-Dropbox*KN2LZ7VXBHZN/db.tt/cchelp/IRL/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-DROPBOX*KN#LZ#VXBHZN/DB.TT/CCHELP/IRL/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-IKEA BULGARIA /SOFIA /BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 66.83 EUR авт.код:202334-IKEA BULGARIA /Sofia /BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-IKEA BULGARIA /SOFIA /BGR/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-OMNIA PHARM/SOFIYA #/TID:P#/PAN:#****#/CT:#/NOM::MBDU ОПЕРАЦИЯ С КАРТА', 'ПОС 34.93 EUR авт.код:051792-OMNIA PHARM/SOFIYA 1421/TID:P5423812/PAN:5408****8235/CT:08/NOM::MBDU Операция с карта', 'POS # EUR AUTH CODE:#-OMNIA PHARM/SOFIYA #/TID:P#/PAN:#****#/CT:#/NOM::MBDU CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR АВТ.КОД:#-SUMUP *EBAG.BG/SOFIIA/BGR/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 52.62 EUR авт.код:606651-SumUp *EBAG.BG/Sofiia/BGR/PAN:5408****8235/CT:08 Операция с карта', 'POS # EUR AUTH CODE:#-SUMUP *EBAG.BG/SOFIIA/BGR/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*#GYWV#D#B#NN/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:128558, Dropbox*2GYWV9D1B4NN/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*#GYWV#D#B#NN/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # EUR, АВТ.КОД:#, DROPBOX*KY#T#P#Y/DB.TT/CCHELP/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 16.66 EUR, авт.код:250843, Dropbox*KY219T357P5Y/db.tt/cchelp/PAN:4106****4666/CT:01 Операция с карта', 'POS # EUR, AUTH CODE:#, DROPBOX*KY#T#P#Y/DB.TT/CCHELP/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # USD АВТ.КОД:#-HIGHLEVEL * TRIAL OVER/DALLAS/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 98.94 USD авт.код:056760-HIGHLEVEL * TRIAL OVER/DALLAS/USA/PAN:5408****6583/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-HIGHLEVEL * TRIAL OVER/DALLAS/USA/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПОС # USD АВТ.КОД:#-QUO (OPENPHONE)/SAN FRANCISCO/USA/PAN:#****#/CT:# ОПЕРАЦИЯ С КАРТА', 'ПОС 552.00 USD авт.код:256432-QUO (OPENPHONE)/SAN FRANCISCO/USA/PAN:5408****6583/CT:08 Операция с карта', 'POS # USD AUTH CODE:#-QUO (OPENPHONE)/SAN FRANCISCO/USA/PAN:#****#/CT:# CARD TRANSACTION', 1, 'mined'),
    ('ПРОФ Ф-РА SF#NSO# OFFICE MATERIALS ИЗХ.ПРЕВОД SEPA В ЕИП', 'проф ф-ра SF01NSO1350064 Office Materials Изх.превод SEPA в ЕИП', 'PROFORMA INVOICE SF#NSO# OFFICE MATERIALS OUTGOING SEPA TRANSFER', 1, 'mined'),
    ('ПРОФОРМА ФАКТУРА ОРИГИНАЛ # / # ДЪ БИ ТИЙМ ООД АКТУАЛИЗИРАНА ПАЗАРНА ОЦЕНКА ПРОФОРМА ФАКТУРА ОРИГИНАЛ # / # ДЪ БИ ТИЙМ ООД АКТУАЛИЗИРАНА ПАЗАРНА ОЦЕНКА /ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ПРОФОРМА ФАКТУРА ОРИГИНАЛ 0000008256 / 19.01.2026 ДЪ БИ ТИЙМ ООД Актуализирана пазарна оценка ПРОФОРМА ФАКТУРА ОРИГИНАЛ 0000008256 / 19.01.2026 ДЪ БИ ТИЙМ ООД Актуализирана пазарна оценка /Издаден вътр.банков превод', 'PROFORMA FAKTURA ORIGINAL # / # DA BI TIYM OOD AKTUALIZIRANA PAZARNA OTSENKA PROFORMA FAKTURA ORIGINAL # / # DA BI TIYM OOD AKTUALIZIRANA PAZARNA OTSENKA /INTERNAL BANK TRANSFER ISSUED', 1, 'mined'),
    ('РЕВИЗИОНЕН АКТ ЗА НАЧЕТ ИЗХ.ПРЕВОД SEPA В ЕИП', 'РЕВИЗИОНЕН АКТ ЗА НАЧЕТ Изх.превод SEPA в ЕИП', 'AUDIT ASSESSMENT ACT OUTGOING SEPA TRANSFER', 1, 'mined'),
    ('ТАКСА ЗА УПРАВЛЕНИЕ НА КРЕДИТ', 'Такса за управление на кредит', 'TAKSA ZA UPRAVLENIE NA KREDIT', 1, 'mined'),
    ('Ф-РА # - CANDLES WOMENS DAY ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000000375 - candles womens day Издаден вътр.банков превод', 'INVOICE # - CANDLES WOMENS DAY INTERNAL BANK TRANSFER ISSUED', 1, 'mined'),
    ('Ф-РА # ACCOUNTING SERVICES DEC # ИЗХ.ПРЕВОД SEPA В ЕИП', 'ф-ра 2000000168 accounting services Dec 2025 Изх.превод SEPA в ЕИП', 'INVOICE # ACCOUNTING SERVICES DEC # OUTGOING SEPA TRANSFER', 1, 'mined'),
    ('Ф-РА # ACCOUNTING SERVICES FEB # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ф-ра 2000000208 accounting services Feb 2026 BLINK Платежно нареждане извън банката', 'INVOICE # ACCOUNTING SERVICES FEB # BLINK PAYMENT ORDER OUTSIDE THE BANK', 1, 'mined'),
    ('Ф-РА # ACCOUNTING SERVICES JAN # BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ф-ра 2000000188 accounting services Jan 2026 BLINK Платежно нареждане извън банката', 'INVOICE # ACCOUNTING SERVICES JAN # BLINK PAYMENT ORDER OUTSIDE THE BANK', 1, 'mined'),
    ('Ф-РА # FRUITS OFFICE BLINK ПЛАТЕЖНО НАРЕЖДАНЕ ИЗВЪН БАНКАТА', 'ф-ра 0000016649 fruits office BLINK Платежно нареждане извън банката', 'INVOICE # FRUITS OFFICE BLINK PAYMENT ORDER OUTSIDE THE BANK', 1, 'mined'),
    ('Ф-РА # MARTO S HRS NEOCURRENCY ИЗХ.ПРЕВОД SEPA В ЕИП', 'ф-ра 0000000534 Marto s hrs Neocurrency Изх.превод SEPA в ЕИП', 'INVOICE # MARTO S HRS NEOCURRENCY OUTGOING SEPA TRANSFER', 1, 'mined'),
    ('Ф-РА # OFFICE AC MAINT ИЗДАДЕН ВЪТР.БАНКОВ ПРЕВОД', 'ф-ра 0000091345 Office AC Maint Издаден вътр.банков превод', 'INVOICE # OFFICE AC MAINT INTERNAL BANK TRANSFER ISSUED', 1, 'mined'),
    ('Ф-РА # STAN PAYMENT ИЗХ.ПРЕВОД SEPA В ЕИП', 'ф-ра 0000000177 Stan Payment Изх.превод SEPA в ЕИП', 'INVOICE # STAN PAYMENT OUTGOING SEPA TRANSFER', 1, 'mined'),
    ('Ф-РА # XMAS PARTY PHOTOS PRINT ИЗХ.ПРЕВОД SEPA В ЕИП', 'ф-ра 0000000396 Xmas party photos print Изх.превод SEPA в ЕИП', 'INVOICE # XMAS PARTY PHOTOS PRINT OUTGOING SEPA TRANSFER', 1, 'mined')
ON CONFLICT (normalized_key) DO NOTHING;

-- ----------------------------------------------------------------------------
-- expense_vendor_rules  (raw_cyrillic = primary; romanized_en = secondary)
-- ----------------------------------------------------------------------------
INSERT INTO public.expense_vendor_rules
    (match_type, pattern, category_id, priority, hits_in_reference, source)
VALUES
    ('exact', 'Национална Агенция за Приходите', 2, 100, 64, 'raw_cyrillic'),  -- Payroll Taxes
    ('exact', 'СТАНИСЛАВ ВАСИЛЕВ ПЕЙКОВ', 1, 100, 38, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Милен Димитров Анастасов', 1, 100, 36, 'raw_cyrillic'),  -- Payroll
    ('exact', 'АСПАРУХ РУМЕНОВ МАНЧЕВ', 1, 100, 34, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ДИМАНА БОЖИДАРОВА ТРОЕВА', 1, 100, 32, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Теодора Дилинска', 1, 100, 32, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Таня Иванова Ангелинова', 1, 100, 31, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ТОШИТОМО БГ ООД', 5, 100, 31, 'raw_cyrillic'),  -- Vehicle & Mobility
    ('exact', 'АТАНАС МАРИОВ МАРИНОВ', 1, 100, 30, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Валери Николаев Стоянов', 1, 100, 30, 'raw_cyrillic'),  -- Payroll
    ('exact', 'КАЛИН ЕМИЛОВ ТОМАНОВ', 1, 100, 30, 'raw_cyrillic'),  -- Payroll
    ('exact', 'UNICREDIT BULBANK', 14, 100, 28, 'raw_cyrillic'),  -- Debt Service
    ('exact', 'МЕЙН АСЕМБЛИ ЕООД', 5, 100, 27, 'raw_cyrillic'),  -- Vehicle & Mobility
    ('exact', 'ЗАСТРАХОВАТЕЛНА КОМПАНИЯ УНИКА ЖИВОТ АД', 8, 100, 26, 'raw_cyrillic'),  -- Employee Benefits
    ('exact', 'ТЕОДОР МАРИАНОВ ДИМИТРОВ', 1, 100, 26, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Надя Бориславова Василева', 1, 100, 25, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ФРАНК ШЕПАЦ', 1, 100, 25, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ДОБРОМИР ВАСИЛЕВ ПЕТРЕВСКИ', 1, 100, 23, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Станимир Христов Димитров', 1, 100, 21, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ТОДОР ЦВЕТКОВ ТОДОРОВ', 1, 100, 20, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ЕЛЕКТРОХОЛД ПРОДАЖБИ ЕАД', 10, 100, 15, 'raw_cyrillic'),  -- Utilities & Facilities
    ('exact', 'КАМЕН БОРИСЛАВОВ КАМЕНОВ', 1, 100, 15, 'raw_cyrillic'),  -- Payroll
    ('exact', 'МАТЮ ДЖИ МАДЕЙ', 1, 100, 15, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ОРБИН ЕООД', 7, 100, 15, 'raw_cyrillic'),  -- Contractors & Agency Fees
    ('exact', 'Тошитомо БГ ООД', 5, 100, 15, 'raw_cyrillic'),  -- Vehicle & Mobility
    ('exact', 'БЕНЕФИТ СИСТЕМС БЪЛГАРИЯ ООД', 8, 100, 14, 'raw_cyrillic'),  -- Employee Benefits
    ('exact', 'КАТАЛИСТ ЕООД', 5, 100, 14, 'raw_cyrillic'),  -- Vehicle & Mobility
    ('exact', 'КАТАЛИСТ ИНТЕРАКТИВ ЕООД', 7, 100, 14, 'raw_cyrillic'),  -- Contractors & Agency Fees
    ('exact', 'Оптимум Акаунтинг ЕООД', 13, 100, 14, 'raw_cyrillic'),  -- Accounting & Compliance
    ('exact', 'РАДОСЛАВ ТОНЕВ ВАРТАНЯНОВ', 1, 100, 13, 'raw_cyrillic'),  -- Payroll
    ('exact', 'УниКредит Булбанк АД', 10, 100, 13, 'raw_cyrillic'),  -- Utilities & Facilities
    ('exact', 'Wise Europe SA', 12, 100, 11, 'raw_cyrillic'),  -- Treasury & Wallet Transfers
    ('exact', 'АЛЕКСАНДЪР АЛЕКСАНДРОВ КЕРЕМИДАРОВ', 1, 100, 10, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Интра Бизнес Сървисиз ЕООД', 9, 100, 10, 'raw_cyrillic'),  -- Office Operations
    ('exact', 'Столична Община Р-н Лозенец', 10, 100, 10, 'raw_cyrillic'),  -- Utilities & Facilities
    ('exact', 'Иван Стоянов Статев', 1, 100, 7, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Пейпър Конвъртинг ЕООД', 6, 100, 6, 'raw_cyrillic'),  -- Office Supplies & Food
    ('exact', 'Wise Europe SA/NV', 12, 100, 5, 'raw_cyrillic'),  -- Treasury & Wallet Transfers
    ('exact', 'Ивайло Станимиров Колев', 1, 100, 5, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ВИМАКС КЛИМА ООД', 9, 100, 4, 'raw_cyrillic'),  -- Office Operations
    ('exact', 'Димитър Димитров Парпулов', 1, 100, 4, 'raw_cyrillic'),  -- Payroll
    ('exact', 'Мартин Русев', 1, 100, 4, 'raw_cyrillic'),  -- Payroll
    ('exact', 'ХРИСТО ПАВЛОВ ДЖАМБОВ', 1, 100, 4, 'raw_cyrillic'),  -- Payroll
    ('exact', 'КООПЕРАЦИЯ ПАНДА', 6, 100, 2, 'raw_cyrillic'),  -- Office Supplies & Food
    ('exact', 'АБИС АЛБА ЕООД', 6, 100, 1, 'raw_cyrillic'),  -- Office Supplies & Food
    ('exact', 'КлаудСорс ООД', 7, 100, 1, 'raw_cyrillic'),  -- Contractors & Agency Fees
    ('exact', 'КОНСУЛТАНТСКА КЪЩА АМРИТА ООД', 13, 100, 1, 'raw_cyrillic'),  -- Accounting & Compliance
    ('exact', 'Мит фрукт 2020 ЕООД', 6, 100, 1, 'raw_cyrillic'),  -- Office Supplies & Food
    ('exact', 'ТД на НОИ София-окръг', 9, 100, 1, 'raw_cyrillic'),  -- Office Operations
    ('exact', 'Хот Колор ЕООД', 9, 100, 1, 'raw_cyrillic'),  -- Office Operations
    ('exact', 'Natsionalna Agentsiya za Prihodite', 2, 200, 64, 'romanized_en'),  -- Payroll Taxes
    ('exact', 'OPENAI *CHATGPT SUBSCR', 3, 200, 59, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'EMAILOCTOPUS', 3, 200, 53, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'TAGGABLE PHOTOS', 3, 200, 46, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'CLAUDE.AI SUBSCRIPTION', 3, 200, 41, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'FIGMA', 3, 200, 39, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'STANISLAV VASILEV PEYKOV', 1, 200, 38, 'romanized_en'),  -- Payroll
    ('exact', 'Milen Dimitrov Anastasov', 1, 200, 36, 'romanized_en'),  -- Payroll
    ('exact', 'ASPARUH RUMENOV MANChEV', 1, 200, 34, 'romanized_en'),  -- Payroll
    ('exact', 'DIMANA BOZhIDAROVA TROEVA', 1, 200, 32, 'romanized_en'),  -- Payroll
    ('exact', 'Teodora Dilinska', 1, 200, 32, 'romanized_en'),  -- Payroll
    ('exact', 'Tanya Ivanova Angelinova', 1, 200, 31, 'romanized_en'),  -- Payroll
    ('exact', 'TOShITOMO BG OOD', 5, 200, 31, 'romanized_en'),  -- Vehicle & Mobility
    ('exact', 'ATANAS MARIOV MARINOV', 1, 200, 30, 'romanized_en'),  -- Payroll
    ('exact', 'KALIN EMILOV TOMANOV', 1, 200, 30, 'romanized_en'),  -- Payroll
    ('exact', 'Valeri Nikolaev Stoyanov', 1, 200, 30, 'romanized_en'),  -- Payroll
    ('exact', 'A1 BULGARIA LTD', 11, 200, 27, 'romanized_en'),  -- Telecom & Internet
    ('exact', 'MEYN ASEMBLI EOOD', 5, 200, 27, 'romanized_en'),  -- Vehicle & Mobility
    ('exact', 'MIDJOURNEY INC.', 3, 200, 27, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'WWW.TWILIO.COM', 3, 200, 27, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'APR*APPRIVER', 3, 200, 26, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'BAMBOOHR HRIS', 3, 200, 26, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'INTUIT *QBOOKS ONLINE', 3, 200, 26, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'TEODOR MARIANOV DIMITROV', 1, 200, 26, 'romanized_en'),  -- Payroll
    ('exact', 'ZASTRAHOVATELNA KOMPANIYa UNIKA ZhIVOT AD', 8, 200, 26, 'romanized_en'),  -- Employee Benefits
    ('exact', 'FRANK ShEPATs', 1, 200, 25, 'romanized_en'),  -- Payroll
    ('exact', 'Nadya Borislavova Vasileva', 1, 200, 25, 'romanized_en'),  -- Payroll
    ('exact', 'SUPERHOSTING.BG BGN', 11, 200, 24, 'romanized_en'),  -- Telecom & Internet
    ('exact', 'DOBROMIR VASILEV PETREVSKI', 1, 200, 23, 'romanized_en'),  -- Payroll
    ('exact', 'EPAY OFFICE1.BG', 9, 200, 22, 'romanized_en'),  -- Office Operations
    ('exact', 'KAFFEKAPSLEN', 6, 200, 21, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'Stanimir Hristov Dimitrov', 1, 200, 21, 'romanized_en'),  -- Payroll
    ('exact', 'DROPBOX', 3, 200, 20, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'INVEST - BG EOOD', 5, 200, 20, 'romanized_en'),  -- Vehicle & Mobility
    ('exact', 'TODOR TsVETKOV TODOROV', 1, 200, 20, 'romanized_en'),  -- Payroll
    ('exact', 'ELEKTROHOLD PRODAZhBI EAD', 10, 200, 15, 'romanized_en'),  -- Utilities & Facilities
    ('exact', 'KAMEN BORISLAVOV KAMENOV', 1, 200, 15, 'romanized_en'),  -- Payroll
    ('exact', 'MATYu DZhI MADEY', 1, 200, 15, 'romanized_en'),  -- Payroll
    ('exact', 'ORBIN EOOD', 7, 200, 15, 'romanized_en'),  -- Contractors & Agency Fees
    ('exact', 'Toshitomo BG OOD', 5, 200, 15, 'romanized_en'),  -- Vehicle & Mobility
    ('exact', 'BENEFIT SISTEMS BALGARIYa OOD', 8, 200, 14, 'romanized_en'),  -- Employee Benefits
    ('exact', 'KATALIST EOOD', 5, 200, 14, 'romanized_en'),  -- Vehicle & Mobility
    ('exact', 'KATALIST INTERAKTIV EOOD', 7, 200, 14, 'romanized_en'),  -- Contractors & Agency Fees
    ('exact', 'Optimum Akaunting EOOD', 13, 200, 14, 'romanized_en'),  -- Accounting & Compliance
    ('exact', 'RADOSLAV TONEV VARTANYaNOV', 1, 200, 13, 'romanized_en'),  -- Payroll
    ('exact', 'UniKredit Bulbank AD', 10, 200, 13, 'romanized_en'),  -- Utilities & Facilities
    ('exact', 'CLICKUP', 3, 200, 11, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'ALEKSANDAR ALEKSANDROV KEREMIDAROV', 1, 200, 10, 'romanized_en'),  -- Payroll
    ('exact', 'Intra Biznes Sarvisiz EOOD', 9, 200, 10, 'romanized_en'),  -- Office Operations
    ('exact', 'Stolichna Obshtina R-n Lozenets', 10, 200, 10, 'romanized_en'),  -- Utilities & Facilities
    ('exact', 'UNICREDIT BULBANK AD', 14, 200, 10, 'romanized_en'),  -- Debt Service
    ('exact', 'FIGMA MONTHLY RENEWAL', 3, 200, 8, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'OPENAI', 3, 200, 8, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'Ivan Stoyanov Statev', 1, 200, 7, 'romanized_en'),  -- Payroll
    ('exact', 'Peypar Konvarting EOOD', 6, 200, 6, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'IKEA BULGARIA', 6, 200, 5, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'Ivaylo Stanimirov Kolev', 1, 200, 5, 'romanized_en'),  -- Payroll
    ('exact', 'Dimitar Dimitrov Parpulov', 1, 200, 4, 'romanized_en'),  -- Payroll
    ('exact', 'HRISTO PAVLOV DZhAMBOV', 1, 200, 4, 'romanized_en'),  -- Payroll
    ('exact', 'Martin Rusev', 1, 200, 4, 'romanized_en'),  -- Payroll
    ('exact', 'S PLYUS S-S. TIMEVA EOO', 6, 200, 4, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'VIMAKS KLIMA OOD', 9, 200, 4, 'romanized_en'),  -- Office Operations
    ('exact', 'HIGHLEVEL INC.', 3, 200, 3, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'RELUME.IO', 3, 200, 3, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'ANTHROPIC', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*151WMP267V1K', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*195YPL8VNXYG', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*2K6LZV4LDK81', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*44CTPN732ZMY', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*5XYYCLN86W1F', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*77FK5B3998XF', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*7L462D8N84TH', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*7N6GYM1HBPDD', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*85LXG4R6VN8Q', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*91FND589SXKW', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*9L7964HZKC89', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*BBMBQGVTVBWV', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*CSF9GNLSB92Y', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*D17Y7ZQBXSK5', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*FCRH7W37L8TY', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*H24JXYJCLZD8', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*H2DDRM6Y74P8', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*HVNFS5HLXS24', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*JKG32PN2S7X6', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*LV71DZFC7H16', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*MVQ1N3R19H4G', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*N9N97BTRMT3T', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*T9V1F26PZKBG', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*VXV7VD69H81H', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*W1N1F2MD5WWM', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*XC2P789Q2VHV', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'ISTYLE.BG', 5, 200, 2, 'romanized_en'),  -- Vehicle & Mobility
    ('exact', 'KOOPERATsIYa PANDA', 6, 200, 2, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'MICROSOFT-G082412259', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G086826006', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G091453138', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G095987214', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G101135623', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G106515158', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G112474622', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G117933017', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G123023626', 3, 200, 2, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'ABIS ALBA EOOD', 6, 200, 1, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'ANTHROPIC SAN FRANCISCO USA 710472', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'BORICA AD', 4, 200, 1, 'romanized_en'),  -- Bank & Transfer Fees
    ('exact', 'DROPBOX*2GYWV9D1B4NN', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*3N2VFZLNNDFV', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*C2B6GZ32DQZ9', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*CQVNVTSF5B4L', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*FHGWH1J4WQVG', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*KN2LZ7VXBHZN', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'DROPBOX*KY219T357P5Y', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'HIGHLEVEL * TRIAL OVER', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'Hot Kolor EOOD', 9, 200, 1, 'romanized_en'),  -- Office Operations
    ('exact', 'KlaudSors OOD', 7, 200, 1, 'romanized_en'),  -- Contractors & Agency Fees
    ('exact', 'KONSULTANTSKA KAShtA AMRITA OOD', 13, 200, 1, 'romanized_en'),  -- Accounting & Compliance
    ('exact', 'MICROSOFT-G134242947', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G139754016', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'MICROSOFT-G145720617', 3, 200, 1, 'romanized_en'),  -- Software & AI Tools
    ('exact', 'Mit frukt 2020 EOOD', 6, 200, 1, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'OMNIA PHARM', 9, 200, 1, 'romanized_en'),  -- Office Operations
    ('exact', 'SUMUP *EBAG.BG', 6, 200, 1, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'SUMUP *EBAG.BG SOFIIA BGR 010066', 6, 200, 1, 'romanized_en'),  -- Office Supplies & Food
    ('exact', 'TD na NOI Sofiya-okrag', 9, 200, 1, 'romanized_en')  -- Office Operations
ON CONFLICT (match_type, pattern) DO NOTHING;

-- ----------------------------------------------------------------------------
-- expense_keyword_rules
-- ----------------------------------------------------------------------------
INSERT INTO public.expense_keyword_rules
    (keyword, category_id, priority, hits_in_reference, force_review)
VALUES
    ('OPENAI', 3, 10, 67, FALSE),  -- Software & AI Tools
    ('CHATGPT', 3, 10, 59, FALSE),  -- Software & AI Tools
    ('FIGMA', 3, 10, 47, FALSE),  -- Software & AI Tools
    ('CLAUDE.AI', 3, 10, 43, FALSE),  -- Software & AI Tools
    ('CURSOR', 3, 10, 28, FALSE),  -- Software & AI Tools
    ('MICROSOFT', 3, 10, 27, FALSE),  -- Software & AI Tools
    ('TWILIO', 3, 10, 27, FALSE),  -- Software & AI Tools
    ('GITHUB', 3, 10, 22, FALSE),  -- Software & AI Tools
    ('GODADDY', 3, 10, 9, FALSE),  -- Software & AI Tools
    ('DROPBOX', 3, 15, 79, FALSE),  -- Software & AI Tools
    ('OPENAI *CHATGPT SUBSCR', 3, 15, 59, FALSE),  -- Software & AI Tools
    ('EMAILOCTOPUS', 3, 15, 53, FALSE),  -- Software & AI Tools
    ('TAGGABLE PHOTOS', 3, 15, 46, FALSE),  -- Software & AI Tools
    ('CLAUDE.AI SUBSCRIPTION', 3, 15, 43, FALSE),  -- Software & AI Tools
    ('A1 BULGARIA LTD', 11, 15, 27, FALSE),  -- Telecom & Internet
    ('MIDJOURNEY INC.', 3, 15, 27, FALSE),  -- Software & AI Tools
    ('WWW.TWILIO.COM', 3, 15, 27, FALSE),  -- Software & AI Tools
    ('APR*APPRIVER', 3, 15, 26, FALSE),  -- Software & AI Tools
    ('BAMBOOHR HRIS', 3, 15, 26, FALSE),  -- Software & AI Tools
    ('INTUIT *QBOOKS ONLINE', 3, 15, 26, FALSE),  -- Software & AI Tools
    ('SUPERHOSTING.BG BGN', 11, 15, 24, FALSE),  -- Telecom & Internet
    ('EPAY OFFICE1.BG', 9, 15, 22, FALSE),  -- Office Operations
    ('KAFFEKAPSLEN', 6, 15, 21, FALSE),  -- Office Supplies & Food
    ('INVEST - BG EOOD', 5, 15, 20, FALSE),  -- Vehicle & Mobility
    ('CLICKUP', 3, 15, 11, FALSE),  -- Software & AI Tools
    ('UNICREDIT BULBANK', 14, 15, 10, TRUE),  -- Debt Service  -- FORCE REVIEW: broad bank-name substring
    ('UNICREDIT BULBANK AD', 14, 15, 10, TRUE),  -- Debt Service  -- FORCE REVIEW: broad bank-name substring
    ('FIGMA MONTHLY RENEWAL', 3, 15, 8, FALSE),  -- Software & AI Tools
    ('IKEA BULGARIA', 6, 15, 5, FALSE),  -- Office Supplies & Food
    ('S PLYUS S-S. TIMEVA EOO', 6, 15, 4, FALSE),  -- Office Supplies & Food
    ('ANTHROPIC', 3, 15, 3, FALSE),  -- Software & AI Tools
    ('HIGHLEVEL INC.', 3, 15, 3, FALSE),  -- Software & AI Tools
    ('RELUME.IO', 3, 15, 3, FALSE),  -- Software & AI Tools
    ('AZV-COMMISSION', 4, 20, 92, FALSE),  -- Bank & Transfer Fees
    ('ТАКСИ ПОЛУЧЕНИ ВАЛУТНИ', 4, 20, 64, FALSE),  -- Bank & Transfer Fees
    ('AGENT SERVIC', 7, 20, 26, FALSE),  -- Contractors & Agency Fees
    ('MAIN ASSEMBLY', 7, 20, 26, FALSE),  -- Contractors & Agency Fees
    ('SALARY', 1, 30, 754, FALSE),  -- Payroll
    ('ЗАПЛАТА', 1, 30, 390, FALSE)  -- Payroll
ON CONFLICT (keyword) DO NOTHING;

COMMIT;
