-- ============================================================================
-- Migration 128: Expense Mapping DELTA (GENERATED — do not hand-edit)
-- ============================================================================
-- Generated by `scripts/expenses/mine_expenses.py --delta`. Additive-only:
-- migration 127 is already applied to prod and is NOT regenerated. These are
-- shorter merchant-descriptor keyword variants that the seed's clean-vendor-
-- name keywords fail to substring-match in real card/POS description lines,
-- so matching rows fell through to Miscellaneous (category 15) at ingest.
-- Validated rows meet the seed bar (>=3 reference hits, >=90% dominance, a
-- non-15 dominant category); exception rows carry an inline justification.
-- Idempotent: ON CONFLICT (keyword) DO NOTHING. No vendor->category-15 rules.
-- ============================================================================

BEGIN;

INSERT INTO public.expense_keyword_rules
    (keyword, category_id, priority, hits_in_reference, force_review)
VALUES
    ('DROPBOX', 3, 10, 79, FALSE),  -- Software & AI Tools :: validated (>=3 hits, >=90% dominance)
    ('A1.BG', 11, 15, 0, FALSE),  -- Telecom & Internet :: EXCEPTION: vendor A1 -> Telecom & Internet 27/27 in reference; POS domain variant of seeded 'A1 BULGARIA LTD'
    ('HIGHLEVEL', 3, 15, 4, FALSE),  -- Software & AI Tools :: validated (>=3 hits, >=90% dominance)
    ('KAFFEK', 6, 15, 21, FALSE),  -- Office Supplies & Food :: validated (>=3 hits, >=90% dominance)
    ('OFFICE1.BG', 9, 15, 22, FALSE),  -- Office Operations :: validated (>=3 hits, >=90% dominance)
    ('RECURRING FEE DUE', 4, 20, 0, FALSE),  -- Bank & Transfer Fees :: EXCEPTION: owner-named English literal; matches description_translated only; inert on current Cyrillic prod (future-proof)
    ('TAKSA ZA OUTGOING SEPA TRANSFER', 4, 20, 0, FALSE),  -- Bank & Transfer Fees :: EXCEPTION: owner-named English literal; matches description_translated only; inert on current Cyrillic prod (future-proof)
    ('ПЕРИОДИЧНА ТАКСА', 4, 20, 25, FALSE),  -- Bank & Transfer Fees :: validated (>=3 hits, >=90% dominance)
    ('ТАКСА ЗА ИЗХ.ПРЕВОД SEPA', 4, 20, 23, FALSE)  -- Bank & Transfer Fees :: validated (>=3 hits, >=90% dominance)
ON CONFLICT (keyword) DO NOTHING;

COMMIT;
